/* =========================================================
   한글 Quest — content data
   Edit this file to change letters, mnemonics, lessons and words.
   Consonants are shown in RED, vowels in BLUE (like the taegeuk).
   Stroke data uses a 100 × 100 grid: each stroke is a list of [x, y] points.
   ========================================================= */
(function () {
  // circle helper for ㅇ / ㅎ — starts at the top and goes anticlockwise
  function circle(cx, cy, r) {
    const pts = [];
    for (let i = 0; i <= 36; i++) {
      const a = -Math.PI / 2 - (i / 36) * Math.PI * 2;
      pts.push([cx + r * Math.cos(a), cy + r * Math.sin(a)]);
    }
    return pts;
  }

  const letters = {
    /* ---------- Stage 1: simple vowels + ㅇ ---------- */
    'ㅇ': { type: 'con', rom: 'silent / ng', name: '이응', sample: '아', img: 'mn-ieung', emoji: '💍',
      mnemonic: 'A golden ring with a bell inside. At the start of a block the bell is silent (a zero!). At the bottom of a block it rings: "ng", like ri-NG!',
      tip: 'Every Korean block must start with a consonant. When a syllable starts with a vowel sound, ㅇ holds the spot silently.',
      strokes: [circle(50, 50, 32)] },
    'ㅣ': { type: 'vow', rom: 'i', name: '이', sample: '이', img: 'mn-i', emoji: '🌲',
      mnemonic: 'A tall, straight tree: "EE-normous tree!"',
      tip: 'Sounds like "ee" in "see".',
      strokes: [[[50, 10], [50, 90]]] },
    'ㅏ': { type: 'vow', rom: 'a', name: '아', sample: '아', img: 'mn-a', emoji: '🌅',
      mnemonic: 'The tree has a branch pointing right, toward the rising sun: "AH, the sun!"',
      tip: 'Sounds like "a" in "father".',
      strokes: [[[40, 10], [40, 90]], [[40, 50], [72, 50]]] },
    'ㅓ': { type: 'vow', rom: 'eo', name: '어', sample: '어', img: 'mn-eo', emoji: '🐦',
      mnemonic: 'The branch points back to the left, away from the sun. The bird looks around: "Where has the sun GONE?"',
      tip: 'Sounds like the "o" in "gone" or "hot". Keep your mouth open and relaxed. Don’t round your lips into an "oh" (that’s ㅗ). Written "eo" in English letters.',
      strokes: [[[28, 50], [60, 50]], [[60, 10], [60, 90]]] },
    'ㅗ': { type: 'vow', rom: 'o', name: '오', sample: '오', img: 'mn-o', emoji: '⭐',
      mnemonic: 'A stick poking UP from the ground: "OH! Look up!"',
      tip: 'Sounds like "o" in "go", with rounded lips.',
      strokes: [[[50, 30], [50, 60]], [[14, 60], [86, 60]]] },
    'ㅜ': { type: 'vow', rom: 'u', name: '우', sample: '우', img: 'mn-u', emoji: '🪱',
      mnemonic: 'A root growing DOWN into the soil: "OO, it’s underground!"',
      tip: 'Sounds like "oo" in "moon".',
      strokes: [[[14, 40], [86, 40]], [[50, 40], [50, 74]]] },
    'ㅡ': { type: 'vow', rom: 'eu', name: '으', sample: '으', img: 'mn-eu', emoji: '😖',
      mnemonic: 'A flat, grumpy, closed mouth: "EUgh."',
      tip: 'Smile with your teeth almost together and say "oo" without rounding your lips. No English word has this exact sound.',
      strokes: [[[14, 50], [86, 50]]] },

    /* ---------- Stage 2 ---------- */
    'ㄱ': { type: 'con', rom: 'g / k', name: '기역', sample: '가', img: 'mn-giyeok', emoji: '🦒',
      mnemonic: 'A giraffe bending its long neck down to graze. G for Giraffe!',
      tip: 'Between "g" and "k". At the very start of a word it sounds closer to a soft "k".',
      strokes: [[[20, 20], [80, 20], [80, 86]]] },
    'ㄴ': { type: 'con', rom: 'n', name: '니은', sample: '나', img: 'mn-nieun', emoji: '👃',
      mnemonic: 'A nose seen from the side. N for Nose!',
      tip: 'Just like the English "n".',
      strokes: [[[24, 14], [24, 80], [86, 80]]] },
    'ㄷ': { type: 'con', rom: 'd / t', name: '디귿', sample: '다', img: 'mn-digeut', emoji: '🦆',
      mnemonic: 'A duck’s wide-open bill. D for Duck!',
      tip: 'Between "d" and "t". At the start of a word it sounds closer to a soft "t".',
      strokes: [[[24, 20], [80, 20]], [[24, 20], [24, 80], [86, 80]]] },
    'ㄹ': { type: 'con', rom: 'r / l', name: '리을', sample: '라', img: 'mn-rieul', emoji: '🐍',
      mnemonic: 'A rattlesnake zig-zagging. R for Rattlesnake (and it can Lie still: L).',
      tip: 'A quick tongue-flick "r" between vowels, and an "l" at the end of a syllable.',
      strokes: [[[20, 14], [80, 14], [80, 48]], [[20, 48], [80, 48]], [[20, 48], [20, 86], [86, 86]]] },
    'ㅁ': { type: 'con', rom: 'm', name: '미음', sample: '마', img: 'mn-mieum', emoji: '👄',
      mnemonic: 'A square mouth going "MMM, yummy!"',
      tip: 'Just like the English "m".',
      strokes: [[[20, 20], [20, 82]], [[20, 20], [80, 20], [80, 82]], [[20, 82], [80, 82]]] },

    /* ---------- Stage 3 ---------- */
    'ㅂ': { type: 'con', rom: 'b / p', name: '비읍', sample: '바', img: 'mn-bieup', emoji: '🪣',
      mnemonic: 'A bucket with two handles sticking up. B for Bucket!',
      tip: 'Between "b" and "p". At the start of a word it sounds closer to a soft "p".',
      strokes: [[[26, 14], [26, 86]], [[74, 14], [74, 86]], [[26, 46], [74, 46]], [[26, 86], [74, 86]]] },
    'ㅅ': { type: 'con', rom: 's', name: '시옷', sample: '사', img: 'mn-siot', emoji: '🛝',
      mnemonic: 'A seesaw with its peak at the top. S for Seesaw!',
      tip: 'Like "s". Before ㅣ it becomes "sh": 시 = "shi".',
      strokes: [[[50, 14], [18, 86]], [[48, 44], [82, 86]]] },
    'ㅈ': { type: 'con', rom: 'j', name: '지읒', sample: '자', img: 'mn-jieut', emoji: '🤹',
      mnemonic: 'A juggler with arms stretched out flat and legs spread. J for Juggler!',
      tip: 'Like "j" in "jump", but softer.',
      strokes: [[[18, 20], [82, 20]], [[50, 20], [18, 86]], [[48, 50], [82, 86]]] },
    'ㅎ': { type: 'con', rom: 'h', name: '히읗', sample: '하', img: 'mn-hieut', emoji: '🎩',
      mnemonic: 'A round face wearing a tall hat. H for Hat!',
      tip: 'Like the English "h".',
      strokes: [[[50, 8], [50, 22]], [[18, 30], [82, 30]], circle(50, 64, 22)] },

    /* ---------- Stage 4: add a stroke = add a puff of air ---------- */
    // pair: the plain letter this one grows from (used for "which one did you hear?" questions)
    'ㅋ': { type: 'con', rom: 'k', name: '키읔', sample: '카', img: 'mn-kieuk', emoji: '🪁', pair: 'ㄱ',
      mnemonic: 'The giraffe from ㄱ is flying a kite, and the string crosses its neck. K for Kite! One extra line = one extra puff of air.',
      tip: 'A strong "k" with a puff of air, like in "kite". Hold a tissue in front of your mouth and it should flutter. ㄱ (가) is softer, with no puff.',
      strokes: [[[20, 18], [80, 18], [80, 86]], [[22, 50], [80, 50]]] },
    'ㅌ': { type: 'con', rom: 't', name: '티읕', sample: '타', img: 'mn-tieut', emoji: '📚', pair: 'ㄷ',
      mnemonic: 'It’s ㄷ with an extra shelf in the middle: a tall bookshelf. T for Tall shelf!',
      tip: 'A strong "t" with a puff of air, like in "top". ㄷ (다) is softer, with no puff.',
      strokes: [[[24, 16], [80, 16]], [[24, 48], [78, 48]], [[24, 16], [24, 84], [86, 84]]] },
    'ㅍ': { type: 'con', rom: 'p', name: '피읖', sample: '파', img: 'mn-pieup', emoji: '🧺', pair: 'ㅂ',
      mnemonic: 'A picnic table: a flat top, two legs and a long bench. P for Picnic!',
      tip: 'A strong "p" with a puff of air, like in "pop". ㅂ (바) is softer, with no puff.',
      strokes: [[[16, 18], [84, 18]], [[34, 18], [38, 80]], [[66, 18], [62, 80]], [[12, 82], [88, 82]]] },
    'ㅊ': { type: 'con', rom: 'ch', name: '치읓', sample: '차', img: 'mn-chieut', emoji: '👑', pair: 'ㅈ',
      mnemonic: 'The juggler from ㅈ won the contest. Look at the crown on top! CH for CHampion!',
      tip: 'A strong "ch" with a puff of air, like in "church". ㅈ (자) is softer, with no puff.',
      strokes: [[[50, 6], [50, 20]], [[18, 28], [82, 28]], [[50, 28], [18, 88]], [[48, 56], [82, 88]]] },

    /* ---------- Stage 5: add a stroke = add a Y ---------- */
    'ㅑ': { type: 'vow', rom: 'ya', name: '야', sample: '야', img: 'mn-ya', emoji: '🐦', pair: 'ㅏ',
      mnemonic: 'Two happy birds on two branches pointing right, cheering "YA! YA!" Two branches = add a Y to ㅏ.',
      tip: 'Say "ya" as in "yard". It’s ㅏ with a quick "y" in front.',
      strokes: [[[40, 10], [40, 90]], [[40, 38], [70, 38]], [[40, 62], [70, 62]]] },
    'ㅕ': { type: 'vow', rom: 'yeo', name: '여', sample: '여', img: 'mn-yeo', emoji: '🐤', pair: 'ㅓ',
      mnemonic: 'Two curious birds on branches pointing left, looking for the sun: "YO-nder, where has it gone?" Two branches = add a Y to ㅓ.',
      tip: 'Say "yo" as in "yonder", with an open, relaxed mouth. It’s ㅓ (the "o" in "gone") with a "y" in front.',
      strokes: [[[28, 38], [58, 38]], [[28, 62], [58, 62]], [[60, 10], [60, 90]]] },
    'ㅛ': { type: 'vow', rom: 'yo', name: '요', sample: '요', img: 'mn-yo', emoji: '🚀', pair: 'ㅗ',
      mnemonic: 'Two rockets pointing UP, ready to blast off: "YO-YO, look up!" Two sticks up = add a Y to ㅗ.',
      tip: 'Say "yo" as in "yo-yo", with rounded lips. It’s ㅗ with a "y" in front.',
      strokes: [[[36, 30], [36, 60]], [[64, 30], [64, 60]], [[14, 60], [86, 60]]] },
    'ㅠ': { type: 'vow', rom: 'yu', name: '유', sample: '유', img: 'mn-yu', emoji: '🌱', pair: 'ㅜ',
      mnemonic: 'Two roots growing DOWN, with two worms waving: "YOU found us!" Two roots = add a Y to ㅜ.',
      tip: 'Say "you". It’s ㅜ with a "y" in front.',
      strokes: [[[14, 40], [86, 40]], [[36, 40], [36, 74]], [[64, 40], [64, 74]]] },

    /* ---------- Stage 6: double letters = tight sounds ---------- */
    'ㄲ': { type: 'con', rom: 'kk', name: '쌍기역', sample: '까', img: 'concept-tense', emoji: '💂', pair: 'ㄱ',
      mnemonic: 'Two ㄱ giraffes standing stiff like soldiers. Double letter = a tight, tense sound with NO puff of air.',
      tip: 'Tighten your throat and say a sharp "k", like the "k" in "skate" (no puff). Compare: 가 (soft), 카 (puff), 까 (tight).',
      strokes: [[[8, 20], [44, 20], [44, 86]], [[54, 20], [92, 20], [92, 86]]] },
    'ㄸ': { type: 'con', rom: 'tt', name: '쌍디귿', sample: '따', img: 'concept-tense', emoji: '💂', pair: 'ㄷ',
      mnemonic: 'Two ㄷ duck bills side by side, stiff as soldiers. Double letter = tight sound, no puff.',
      tip: 'A sharp "t", like the "t" in "stop" (no puff). Compare: 다, 타, 따.',
      strokes: [[[10, 20], [44, 20]], [[10, 20], [10, 80], [46, 80]], [[56, 20], [90, 20]], [[56, 20], [56, 80], [92, 80]]] },
    'ㅃ': { type: 'con', rom: 'pp', name: '쌍비읍', sample: '빠', img: 'concept-tense', emoji: '💂', pair: 'ㅂ',
      mnemonic: 'Two ㅂ buckets standing to attention. Double letter = tight sound, no puff. You already know it from 아빠 (dad)!',
      tip: 'A sharp "p", like the "p" in "spin" (no puff). Compare: 바, 파, 빠.',
      strokes: [[[10, 14], [10, 86]], [[40, 14], [40, 86]], [[10, 46], [40, 46]], [[10, 86], [40, 86]], [[58, 14], [58, 86]], [[88, 14], [88, 86]], [[58, 46], [88, 46]], [[58, 86], [88, 86]]] },
    'ㅆ': { type: 'con', rom: 'ss', name: '쌍시옷', sample: '싸', img: 'concept-tense', emoji: '💂', pair: 'ㅅ',
      mnemonic: 'Two ㅅ seesaws side by side, stiff and straight. Double letter = a strong, hissing "ss".',
      tip: 'A strong, hissing "s", like a snake: "sss". Compare: 사 (soft) and 싸 (tight).',
      strokes: [[[30, 14], [8, 86]], [[28, 44], [46, 86]], [[72, 14], [52, 86]], [[70, 44], [92, 86]]] },
    'ㅉ': { type: 'con', rom: 'jj', name: '쌍지읒', sample: '짜', img: 'concept-tense', emoji: '💂', pair: 'ㅈ',
      mnemonic: 'Two ㅈ jugglers standing stiff like soldiers. Double letter = tight sound, no puff.',
      tip: 'A sharp, tight "j", a bit like the "ts" in "cats". Compare: 자, 차, 짜.',
      strokes: [[[6, 20], [44, 20]], [[26, 20], [6, 86]], [[25, 48], [44, 86]], [[56, 20], [94, 20]], [[76, 20], [56, 86]], [[75, 48], [94, 86]]] },

    /* ---------- Stage 7: vowel mash-ups ---------- */
    // snd: letters with the same snd sound alike today, so they are never used against each other in listening questions
    'ㅐ': { type: 'vow', rom: 'ae', name: '애', sample: '애', img: 'concept-mashup', emoji: '🥤', snd: 'e',
      mnemonic: 'Blend ㅏ + ㅣ and you get ㅐ. Its little tick sits on the INSIDE, between the two lines.',
      tip: 'Say "e" as in "bed". Today ㅐ and ㅔ sound almost the same, so you learn which one to use by reading the word.',
      strokes: [[[40, 10], [40, 90]], [[40, 50], [58, 50]], [[68, 10], [68, 90]]] },
    'ㅔ': { type: 'vow', rom: 'e', name: '에', sample: '에', img: 'concept-mashup', emoji: '🥤', snd: 'e',
      mnemonic: 'Blend ㅓ + ㅣ and you get ㅔ. Its little tick sits on the OUTSIDE, pointing left.',
      tip: 'Say "e" as in "bed". It sounds the same as ㅐ.',
      strokes: [[[24, 50], [42, 50]], [[44, 10], [44, 90]], [[68, 10], [68, 90]]] },
    'ㅒ': { type: 'vow', rom: 'yae', name: '얘', sample: '얘', img: 'concept-mashup', emoji: '🥤', snd: 'ye',
      mnemonic: 'ㅐ with an extra tick = add a Y (just like ㅏ → ㅑ).',
      tip: 'Say "ye" as in "yes". It sounds almost the same as ㅖ. It’s rare: you’ll mostly see it in 얘기 (a chat).',
      strokes: [[[40, 10], [40, 90]], [[40, 38], [58, 38]], [[40, 62], [58, 62]], [[68, 10], [68, 90]]] },
    'ㅖ': { type: 'vow', rom: 'ye', name: '예', sample: '예', img: 'concept-mashup', emoji: '🥤', snd: 'ye',
      mnemonic: 'ㅔ with an extra tick = add a Y (just like ㅓ → ㅕ).',
      tip: 'Say "ye" as in "yes". 예 is a very polite way to say "yes"!',
      strokes: [[[22, 38], [42, 38]], [[22, 62], [42, 62]], [[44, 10], [44, 90]], [[68, 10], [68, 90]]] },
    'ㅘ': { type: 'vow', rom: 'wa', name: '와', sample: '와', img: 'concept-mashup', emoji: '🥤',
      mnemonic: 'Blend ㅗ + ㅏ: say "o" and "a" really fast… "o-a, o-a, WA!"',
      tip: 'Say "wa" as in "wander". 와! also means "Wow!"',
      strokes: [[[30, 40], [30, 64]], [[8, 64], [54, 64]], [[66, 8], [66, 92]], [[66, 50], [86, 50]]] },
    'ㅙ': { type: 'vow', rom: 'wae', name: '왜', sample: '왜', img: 'concept-mashup', emoji: '🥤', snd: 'we',
      mnemonic: 'Blend ㅗ + ㅐ: "o-e" said fast = "we". 왜? means "Why?"',
      tip: 'Say "we" as in "wet". ㅙ, ㅚ and ㅞ all sound almost the same today.',
      strokes: [[[26, 40], [26, 64]], [[6, 64], [46, 64]], [[56, 8], [56, 92]], [[56, 50], [70, 50]], [[80, 8], [80, 92]]] },
    'ㅚ': { type: 'vow', rom: 'oe', name: '외', sample: '외', img: 'concept-mashup', emoji: '🥤', snd: 'we',
      mnemonic: 'Blend ㅗ + ㅣ. It LOOKS like "o-ee", but it sounds like "we". Tricky one!',
      tip: 'Say "we" as in "wet". You’ll see it in 회사 (company) and 교회 (church).',
      strokes: [[[30, 40], [30, 64]], [[8, 64], [54, 64]], [[72, 8], [72, 92]]] },
    'ㅝ': { type: 'vow', rom: 'wo', name: '워', sample: '워', img: 'concept-mashup', emoji: '🥤',
      mnemonic: 'Blend ㅜ + ㅓ: "oo-o" said fast = "wo", as in "wobble".',
      tip: 'Say "wo" as in "wobble", with an open mouth like ㅓ. 뭐? means "What?"',
      strokes: [[[6, 40], [50, 40]], [[28, 40], [28, 68]], [[54, 56], [70, 56]], [[72, 8], [72, 92]]] },
    'ㅞ': { type: 'vow', rom: 'we', name: '웨', sample: '웨', img: 'concept-mashup', emoji: '🥤', snd: 'we',
      mnemonic: 'Blend ㅜ + ㅔ: "oo-e" said fast = "we". It’s rare. You’ll see it in 웨이터 (waiter).',
      tip: 'Say "we" as in "wet". It sounds the same as ㅙ and ㅚ.',
      strokes: [[[4, 40], [42, 40]], [[22, 40], [22, 68]], [[46, 56], [60, 56]], [[62, 8], [62, 92]], [[82, 8], [82, 92]]] },
    'ㅟ': { type: 'vow', rom: 'wi', name: '위', sample: '위', img: 'concept-mashup', emoji: '🥤',
      mnemonic: 'Blend ㅜ + ㅣ: "oo-ee" said fast = "wee". 위 means "up / on top"!',
      tip: 'Say "wee" as in "week".',
      strokes: [[[6, 40], [54, 40]], [[30, 40], [30, 68]], [[72, 8], [72, 92]]] },
    'ㅢ': { type: 'vow', rom: 'ui', name: '의', sample: '의', img: 'concept-mashup', emoji: '🥤',
      mnemonic: 'Blend ㅡ + ㅣ: the grumpy flat mouth slides into a smile: "eu-ee".',
      tip: 'At the start of a word, say "eu-ee" quickly (의사, doctor). After a consonant it sounds like ㅣ (희 = "hee"). When it means "of", it sounds like ㅔ.',
      strokes: [[[6, 56], [58, 56]], [[72, 8], [72, 92]]] }
  };

  const stages = [
    { id: 1, ko: '모음', title: 'The Six Simple Vowels', blurb: 'The silent circle and the tree family. Read your first words by the end!', letters: ['ㅇ','ㅣ','ㅏ','ㅓ','ㅗ','ㅜ','ㅡ'],
      lessons: [
        { id: '1a', title: 'The silent circle & the tree family', type: 'letters', letters: ['ㅇ','ㅣ','ㅏ','ㅓ'], build: ['아','어','이'],
          intro: 'Every Korean syllable is a little <b>block</b>, and every block must <b>start with a consonant</b>. When a syllable starts with a vowel sound, Korean uses <b class="c-con">ㅇ</b> as a silent placeholder. Let’s meet ㅇ and the tall “tree” vowels.' },
        { id: '1b', title: 'Up, down & grumpy', type: 'letters', letters: ['ㅗ','ㅜ','ㅡ'], build: ['오','우','으','아','이'],
          intro: 'Here’s the block rule: <b>tall vowels</b> stand to the <b>right</b> of the consonant (<span class="ko">아</span>). <b>Flat vowels</b> lie <b>underneath</b> it (<span class="ko">오</span>).' },
        { id: '1c', title: 'First words', type: 'words',
          intro: 'You already know enough letters to read real Korean words! Tap each word to hear it.' }
      ] },
    { id: 2, ko: '자음 1', title: 'The Everyday Five', blurb: 'ㄱ ㄴ ㄷ ㄹ ㅁ: suddenly you can read trees, spiders and mum.', letters: ['ㄱ','ㄴ','ㄷ','ㄹ','ㅁ'],
      lessons: [
        { id: '2a', title: 'Giraffe, nose & duck', type: 'letters', letters: ['ㄱ','ㄴ','ㄷ'], build: ['가','나','다','고','누','디','거'],
          intro: 'Time for consonants! A consonant can’t be said on its own, so we say it with <span class="ko">ㅏ</span>: <span class="ko">가, 나, 다</span>.' },
        { id: '2b', title: 'Snake & mouth', type: 'letters', letters: ['ㄹ','ㅁ'], build: ['라','마','모','루','미','러'],
          intro: 'Two more! <span class="ko">ㄹ</span> is the trickiest sound in Korean: somewhere between r and l.' },
        { id: '2c', title: 'Words: people & places', type: 'words',
          intro: 'Now you can read words like <span class="ko">나무</span> (tree) and <span class="ko">어머니</span> (mother).' }
      ] },
    { id: 3, ko: '자음 2', title: 'The Next Four', blurb: 'ㅂ ㅅ ㅈ ㅎ: lions, the sea, buses and your first sentences.', letters: ['ㅂ','ㅅ','ㅈ','ㅎ'],
      lessons: [
        { id: '3a', title: 'Bucket & seesaw', type: 'letters', letters: ['ㅂ','ㅅ'], build: ['바','사','보','수','시','버'],
          intro: 'Two more consonants. Watch out: <span class="ko">ㅅ</span> changes to “sh” before <span class="ko">ㅣ</span>.' },
        { id: '3b', title: 'Juggler & hat', type: 'letters', letters: ['ㅈ','ㅎ'], build: ['자','하','지','호','주','허'],
          intro: 'The last two letters of Stage 3. After this, the Sentence Workshop is next!' },
        { id: '3c', title: 'Words: animals, sea & family', type: 'words',
          intro: 'Lions, hippos, butterflies and buses: all readable now.' }
      ] },
    { id: 4, ko: '거센소리', title: 'Add a Stroke = Add a Puff', blurb: 'ㅋ ㅌ ㅍ ㅊ and the tissue test: coffee, pizza and trains.', letters: ['ㅋ','ㅌ','ㅍ','ㅊ'],
      lessons: [
        { id: '4a', title: 'Kite & bookshelf', type: 'letters', letters: ['ㅋ','ㅌ'], build: ['카','타','코','토','키','투','커'], img: 'tissue-test',
          intro: 'Here’s a Hangul secret: <b>add one line and you add a puff of air!</b> <span class="ko">ㄱ → ㅋ</span> and <span class="ko">ㄷ → ㅌ</span>. Try the <b>tissue test</b>: hold a tissue in front of your mouth and say <span class="ko">가</span>, then <span class="ko">카</span>. With <span class="ko">카</span>, the tissue flutters!' },
        { id: '4b', title: 'Picnic & champion', type: 'letters', letters: ['ㅍ','ㅊ'], build: ['파','차','포','추','피','치','퍼'], img: 'tissue-test',
          intro: 'Same trick again: <span class="ko">ㅂ → ㅍ</span> and <span class="ko">ㅈ → ㅊ</span>. Extra line, extra puff. Keep that tissue handy!' },
        { id: '4c', title: 'Words: café, pizza & trains', type: 'words',
          intro: 'Lots of these words were borrowed from English. Can you guess them before you tap?' }
      ] },
    { id: 5, ko: 'Y 모음', title: 'Add a Stroke = Add a Y', blurb: 'ㅑ ㅕ ㅛ ㅠ: milk, baseball, tickets and foxes.', letters: ['ㅑ','ㅕ','ㅛ','ㅠ'],
      lessons: [
        { id: '5a', title: 'Two-branch trees', type: 'letters', letters: ['ㅑ','ㅕ'], build: ['야','여','겨','녀','벼','셔','려'],
          intro: 'Another Hangul secret: <b>add a second short stroke to a vowel and it gets a “y” in front!</b> <span class="ko">ㅏ → ㅑ</span> (a → ya) and <span class="ko">ㅓ → ㅕ</span> (eo → yeo).' },
        { id: '5b', title: 'Rockets & roots', type: 'letters', letters: ['ㅛ','ㅠ'], build: ['요','유','교','뉴','표','휴','류'],
          intro: 'Same trick for the flat vowels: <span class="ko">ㅗ → ㅛ</span> (o → yo) and <span class="ko">ㅜ → ㅠ</span> (u → yu). Two sticks = add a “y”.' },
        { id: '5c', title: 'Words: milk, tickets & yoga', type: 'words',
          intro: 'Some really useful trip words here, like <span class="ko">표</span> (ticket) and <span class="ko">무료</span> (free).' }
      ] },
    { id: 6, ko: '된소리', title: 'Double Letters', blurb: 'ㄲ ㄸ ㅃ ㅆ ㅉ: tight, tense sounds. Dad, rabbits and cheap prices.', letters: ['ㄲ','ㄸ','ㅃ','ㅆ','ㅉ'],
      lessons: [
        { id: '6a', title: 'Soldier twins', type: 'letters', letters: ['ㄲ','ㄸ','ㅃ'], build: ['까','따','빠','꼬','뚜','뿌','끼'], img: 'concept-tense',
          intro: 'Double the letter and the sound goes <b>tight and tense</b>, like a soldier standing stiff. <b>No puff of air!</b> Now you know all three “flavours”: <span class="ko">가</span> (soft), <span class="ko">카</span> (puff), <span class="ko">까</span> (tight).' },
        { id: '6b', title: 'Hissing & tight twins', type: 'letters', letters: ['ㅆ','ㅉ'], build: ['싸','짜','쓰','찌','쏘','쪼'], img: 'concept-tense',
          intro: 'Two more twins. <span class="ko">ㅆ</span> is a strong hissing “ss”, and <span class="ko">ㅉ</span> is a tight “jj”. You’ll hear these at the market: <span class="ko">싸요!</span> (It’s cheap!)' },
        { id: '6c', title: 'Words: dad, rabbits & prices', type: 'words',
          intro: 'Listen for the tight sounds as you read.' }
      ] },
    { id: 7, ko: '복합 모음', title: 'Vowel Mash-ups', blurb: 'ㅐ ㅔ ㅘ ㅝ ㅢ and friends: dogs, apples, “why?” and “what?”', letters: ['ㅐ','ㅔ','ㅒ','ㅖ','ㅘ','ㅙ','ㅚ','ㅝ','ㅞ','ㅟ','ㅢ'],
      lessons: [
        { id: '7a', title: 'The “e” family', type: 'letters', letters: ['ㅐ','ㅔ','ㅒ','ㅖ'], build: ['개','게','새','세','내','네','계'], img: 'concept-mashup',
          intro: 'Put two vowels in the blender and you get a new one! <span class="ko">ㅏ+ㅣ = ㅐ</span> and <span class="ko">ㅓ+ㅣ = ㅔ</span>. Good news: today <b>ㅐ and ㅔ sound the same</b> (“e” as in “bed”).' },
        { id: '7b', title: 'The “w” family: o + …', type: 'letters', letters: ['ㅘ','ㅙ','ㅚ'], build: ['과','봐','와','왜','돼','회','뇌'], img: 'concept-mashup',
          intro: 'Start with <span class="ko">ㅗ</span> and blend: say the two sounds really fast and a <b>“w”</b> appears! <span class="ko">ㅗ+ㅏ = ㅘ</span> (wa). Watch out: <span class="ko">ㅙ</span> and <span class="ko">ㅚ</span> (and <span class="ko">ㅞ</span> in the next lesson) all sound like “we”.' },
        { id: '7c', title: 'The “w” family: u + …', type: 'letters', letters: ['ㅝ','ㅞ','ㅟ','ㅢ'], build: ['뭐','워','위','귀','쉬','의','뒤'], img: 'concept-mashup',
          intro: 'Now blend with <span class="ko">ㅜ</span>: <span class="ko">ㅜ+ㅓ = ㅝ</span> (wo) and <span class="ko">ㅜ+ㅣ = ㅟ</span> (wi). Last of all, the tricky <span class="ko">ㅢ</span>. After this you know every vowel in Korean!' },
        { id: '7d', title: 'Words: animals & café', type: 'words', slice: [0, 16],
          intro: 'You can now read every vowel! Time for some tasty words.' },
        { id: '7e', title: 'Words: why, what & weather', type: 'words', slice: [16, 99],
          intro: 'Question words and weather words you’ll use every day in Korea.' }
      ] },
    { id: 8, ko: '받침', title: 'Bottom Letters', blurb: 'The 7 ending sounds: 밥, 김치, 한국, 서울.', letters: [], display: '받침', kind: 'finals',
      lessons: [
        { id: '8a', title: 'Humming & rolling endings', type: 'finals', finals: ['ㄴ','ㅁ','ㅇ','ㄹ'], img: 'concept-batchim',
          listen: [['반','밤','방','발'], ['산','삼','상','살'], ['간','감','강','갈'], ['문','뭄','뭉','물']],
          ask: [['산','ㄴ'], ['곰','ㅁ'], ['강','ㅇ'], ['발','ㄹ'], ['눈','ㄴ'], ['방','ㅇ']],
          build: ['산','밤','강','달','문'],
          intro: 'Some blocks have a <b>bottom letter</b>, called <span class="ko">받침</span> (batchim). Lots of letters can sit at the bottom, but they only make <b>7 sounds</b>, like 7 doors out of a house! First, the 4 you can hold for a long time: <span class="ko c-fin">ㄴ ㅁ ㅇ ㄹ</span>.' },
        { id: '8b', title: 'Stop endings', type: 'finals', finals: ['ㄱ','ㄷ','ㅂ'], doubles: true, img: 'concept-batchim',
          listen: [['박','받','밥','반'], ['국','굳','굽','군'], ['막','맏','맙','맘']],
          ask: [['옷','ㄷ'], ['꽃','ㄷ'], ['낮','ㄷ'], ['밖','ㄱ'], ['앞','ㅂ'], ['책','ㄱ'], ['밥','ㅂ'], ['잎','ㅂ'], ['엌','ㄱ']],
          build: ['집','책','밥','국','박'],
          intro: 'The last 3 doors are <b>stop sounds</b>: <span class="ko c-fin">ㄱ ㄷ ㅂ</span>. You start the sound, then stop it without letting any air out. Lots of letters at the bottom squash into these three. For example, <span class="ko">옷</span> ends with a <span class="ko">ㄷ</span> sound!' },
        { id: '8c', title: 'Words: food, family & home', type: 'words', slice: [0, 12],
          intro: 'Real words with bottom letters. Now you can read almost anything!' },
        { id: '8d', title: 'Words: trip essentials', type: 'words', slice: [12, 99],
          intro: 'The words you’ll need most on the trip: toilets, subways and “how much?”' }
      ] },
    { id: 9, ko: '발음 규칙', title: 'Reading Like a Korean', blurb: 'The sound-change rules native speakers use: 감사합니다 → [감사함니다].', letters: [], display: '발음', kind: 'rules',
      lessons: [
        { id: '9a', title: 'Sliding & humming', type: 'rules', rules: ['link', 'nasal'], img: 'concept-sound-rules',
          intro: 'Korean is <b>written</b> one way but sometimes <b>said</b> a little differently, so it flows smoothly. These are the magic sound rules. Learn them and you’ll sound like a native speaker!' },
        { id: '9b', title: 'Puffs & “ch” sounds', type: 'rules', rules: ['aspir', 'palatal'], img: 'concept-sound-rules',
          intro: 'Two more spells: <span class="ko">ㅎ</span> adds a puff to its neighbour, and <span class="ko">ㄷ/ㅌ</span> + <span class="ko">이</span> turn into “j/ch” sounds.' },
        { id: '9c', title: 'L-sounds & tight sounds', type: 'rules', rules: ['liquid', 'tense'], img: 'concept-sound-rules',
          intro: 'The final two spells. After these, you can read Korean like a pro!' },
        { id: '9d', title: 'Graduation words', type: 'words',
          intro: 'Super-useful words that use the sound rules. Listen closely to how they’re really said.' }
      ] }
  ];

  // for: 'boy' | 'girl' limits a word to one family-word set
  // note: an optional extra fact shown on the word card
  const words = [
    // Stage 1
    { ko: '아이', en: 'child', rom: 'a-i', emoji: '🧒', stage: 1, pack: 'People & family' },
    { ko: '오이', en: 'cucumber', rom: 'o-i', emoji: '🥒', stage: 1, pack: 'Food & drink' },
    { ko: '이', en: 'two (2)', rom: 'i', emoji: '2️⃣', stage: 1, pack: 'Numbers', note: 'A Sino-Korean number, used for dates, money and phone numbers. 이 also means “tooth”!' },
    { ko: '오', en: 'five (5)', rom: 'o', emoji: '5️⃣', stage: 1, pack: 'Numbers', note: 'A Sino-Korean number.' },
    // Stage 2
    { ko: '나', en: 'I / me (casual)', rom: 'na', emoji: '🙋', stage: 2, pack: 'People & family', note: 'Use with friends. The polite word is 저.' },
    { ko: '너', en: 'you (casual)', rom: 'neo', emoji: '👉', stage: 2, pack: 'People & family', note: 'Only for close friends your age or younger.' },
    { ko: '나무', en: 'tree', rom: 'na-mu', emoji: '🌳', stage: 2, pack: 'Weather & nature' },
    { ko: '거미', en: 'spider', rom: 'geo-mi', emoji: '🕷️', stage: 2, pack: 'Animals' },
    { ko: '머리', en: 'head / hair', rom: 'meo-ri', emoji: '💇', stage: 2, pack: 'Body & health' },
    { ko: '다리', en: 'leg / bridge', rom: 'da-ri', emoji: '🦵', stage: 2, pack: 'Body & health' },
    { ko: '고기', en: 'meat', rom: 'go-gi', emoji: '🥩', stage: 2, pack: 'Food & drink', note: 'You’ll hear this a lot at Korean BBQ: 고기 means meat!' },
    { ko: '오리', en: 'duck', rom: 'o-ri', emoji: '🦆', stage: 2, pack: 'Animals' },
    { ko: '나라', en: 'country', rom: 'na-ra', emoji: '🌏', stage: 2, pack: 'Airport, hotel & travel' },
    { ko: '라디오', en: 'radio', rom: 'ra-di-o', emoji: '📻', stage: 2, pack: 'Home & objects' },
    { ko: '어머니', en: 'mother', rom: 'eo-meo-ni', emoji: '👩', stage: 2, pack: 'People & family', note: 'At home, children usually say 엄마 (mum).' },
    { ko: '누나', en: 'older sister (a boy says)', rom: 'nu-na', emoji: '👧', stage: 2, pack: 'People & family', for: 'boy', note: 'Boys call an older sister (or older girl friend) 누나.' },
    { ko: '이모', en: 'aunty (mum’s sister)', rom: 'i-mo', emoji: '👩‍🦰', stage: 2, pack: 'People & family', note: 'Koreans also call a friendly restaurant lady 이모!' },
    { ko: '누구', en: 'who?', rom: 'nu-gu', emoji: '❓', stage: 2, pack: 'Question words' },
    { ko: '어디', en: 'where?', rom: 'eo-di', emoji: '📍', stage: 2, pack: 'Question words', note: 'Super useful on the trip: “화장실 어디예요?” = Where is the toilet?' },
    { ko: '구', en: 'nine (9)', rom: 'gu', emoji: '9️⃣', stage: 2, pack: 'Numbers', note: 'A Sino-Korean number.' },
    { ko: '너무', en: 'very / too much', rom: 'neo-mu', emoji: '💯', stage: 2, pack: 'Describing words' },
    // Stage 3
    { ko: '바다', en: 'sea', rom: 'ba-da', emoji: '🌊', stage: 3, pack: 'Weather & nature' },
    { ko: '사자', en: 'lion', rom: 'sa-ja', emoji: '🦁', stage: 3, pack: 'Animals' },
    { ko: '모자', en: 'hat / cap', rom: 'mo-ja', emoji: '🧢', stage: 3, pack: 'Clothes & colours' },
    { ko: '하나', en: 'one (1)', rom: 'ha-na', emoji: '☝️', stage: 3, pack: 'Numbers', note: 'A native Korean number, used for counting things and ages.' },
    { ko: '바지', en: 'trousers', rom: 'ba-ji', emoji: '👖', stage: 3, pack: 'Clothes & colours' },
    { ko: '두부', en: 'tofu', rom: 'du-bu', emoji: '🍲', stage: 3, pack: 'Food & drink' },
    { ko: '지도', en: 'map', rom: 'ji-do', emoji: '🗺️', stage: 3, pack: 'Transport & directions' },
    { ko: '하마', en: 'hippo', rom: 'ha-ma', emoji: '🦛', stage: 3, pack: 'Animals' },
    { ko: '가수', en: 'singer', rom: 'ga-su', emoji: '🎤', stage: 3, pack: 'Korean culture', note: 'K-pop stars are 가수!' },
    { ko: '버스', en: 'bus', rom: 'beo-seu', emoji: '🚌', stage: 3, pack: 'Transport & directions', note: 'English words borrowed into Korean often end in ㅡ: 버스 (bus), 주스 (juice).' },
    { ko: '비', en: 'rain', rom: 'bi', emoji: '🌧️', stage: 3, pack: 'Weather & nature' },
    { ko: '아버지', en: 'father', rom: 'a-beo-ji', emoji: '👨', stage: 3, pack: 'People & family', note: 'At home, children usually say 아빠 (dad).' },
    { ko: '부모', en: 'parents', rom: 'bu-mo', emoji: '👪', stage: 3, pack: 'People & family' },
    { ko: '소', en: 'cow', rom: 'so', emoji: '🐄', stage: 3, pack: 'Animals' },
    { ko: '사', en: 'four (4)', rom: 'sa', emoji: '4️⃣', stage: 3, pack: 'Numbers', note: 'A Sino-Korean number.' },
    { ko: '나비', en: 'butterfly', rom: 'na-bi', emoji: '🦋', stage: 3, pack: 'Animals' },
    { ko: '주스', en: 'juice', rom: 'ju-seu', emoji: '🧃', stage: 3, pack: 'Food & drink' },
    { ko: '허리', en: 'waist / lower back', rom: 'heo-ri', emoji: '🤸', stage: 3, pack: 'Body & health' },
    { ko: '모두', en: 'everyone / all', rom: 'mo-du', emoji: '🙌', stage: 3, pack: 'Describing words' },
    { ko: '하루', en: 'one day', rom: 'ha-ru', emoji: '📅', stage: 3, pack: 'Time & days' },
    // Stage 4
    { ko: '코', en: 'nose', rom: 'ko', emoji: '👃', stage: 4, pack: 'Body & health' },
    { ko: '키', en: 'height / key', rom: 'ki', emoji: '📏', stage: 4, pack: 'Body & health', note: '“키가 커요” means “(someone) is tall”.' },
    { ko: '커피', en: 'coffee', rom: 'keo-pi', emoji: '☕', stage: 4, pack: 'Restaurant & café', note: 'Borrowed from English! Many Korean words are: 커피, 피자, 버터, 스키…' },
    { ko: '차', en: 'tea / car', rom: 'cha', emoji: '🍵', stage: 4, pack: 'Restaurant & café', note: '차 means both tea and car. The sentence tells you which!' },
    { ko: '기차', en: 'train', rom: 'gi-cha', emoji: '🚆', stage: 4, pack: 'Transport & directions', note: 'Korea’s fast train is the KTX.' },
    { ko: '포도', en: 'grapes', rom: 'po-do', emoji: '🍇', stage: 4, pack: 'Food & drink' },
    { ko: '토마토', en: 'tomato', rom: 'to-ma-to', emoji: '🍅', stage: 4, pack: 'Food & drink' },
    { ko: '피자', en: 'pizza', rom: 'pi-ja', emoji: '🍕', stage: 4, pack: 'Food & drink' },
    { ko: '치즈', en: 'cheese', rom: 'chi-jeu', emoji: '🧀', stage: 4, pack: 'Food & drink', note: 'Koreans say “치즈!” when taking photos, just like “cheese!”' },
    { ko: '버터', en: 'butter', rom: 'beo-teo', emoji: '🧈', stage: 4, pack: 'Food & drink' },
    { ko: '고추', en: 'chilli pepper', rom: 'go-chu', emoji: '🌶️', stage: 4, pack: 'Food & drink', note: 'Gochujang (고추장) is the spicy red paste in lots of Korean food.' },
    { ko: '포크', en: 'fork', rom: 'po-keu', emoji: '🍴', stage: 4, pack: 'Restaurant & café', note: 'Most Korean restaurants give you chopsticks (젓가락) and a spoon.' },
    { ko: '치마', en: 'skirt', rom: 'chi-ma', emoji: '👗', stage: 4, pack: 'Clothes & colours' },
    { ko: '카드', en: 'card', rom: 'ka-deu', emoji: '💳', stage: 4, pack: 'Shopping & money', note: '“카드 돼요?” = Can I pay by card?' },
    { ko: '파티', en: 'party', rom: 'pa-ti', emoji: '🎉', stage: 4, pack: 'School & hobbies' },
    { ko: '피아노', en: 'piano', rom: 'pi-a-no', emoji: '🎹', stage: 4, pack: 'School & hobbies' },
    { ko: '스키', en: 'skiing', rom: 'seu-ki', emoji: '⛷️', stage: 4, pack: 'School & hobbies' },
    { ko: '타조', en: 'ostrich', rom: 'ta-jo', emoji: '🦤', stage: 4, pack: 'Animals' },
    { ko: '치타', en: 'cheetah', rom: 'chi-ta', emoji: '🐆', stage: 4, pack: 'Animals' },
    // Stage 5
    { ko: '야구', en: 'baseball', rom: 'ya-gu', emoji: '⚾', stage: 5, pack: 'School & hobbies', note: 'Baseball is hugely popular in Korea!' },
    { ko: '여자', en: 'woman / girl', rom: 'yeo-ja', emoji: '👩', stage: 5, pack: 'People & family' },
    { ko: '요리', en: 'cooking', rom: 'yo-ri', emoji: '🍳', stage: 5, pack: 'School & hobbies' },
    { ko: '우유', en: 'milk', rom: 'u-yu', emoji: '🥛', stage: 5, pack: 'Food & drink' },
    { ko: '휴지', en: 'tissue / toilet paper', rom: 'hyu-ji', emoji: '🧻', stage: 5, pack: 'Home & objects' },
    { ko: '교사', en: 'teacher', rom: 'gyo-sa', emoji: '👩‍🏫', stage: 5, pack: 'People & family' },
    { ko: '여기', en: 'here', rom: 'yeo-gi', emoji: '👇', stage: 5, pack: 'Transport & directions', note: '“여기요!” is how you politely call a waiter.' },
    { ko: '거기', en: 'there', rom: 'geo-gi', emoji: '👉', stage: 5, pack: 'Transport & directions' },
    { ko: '여우', en: 'fox', rom: 'yeo-u', emoji: '🦊', stage: 5, pack: 'Animals' },
    { ko: '우표', en: 'stamp', rom: 'u-pyo', emoji: '📮', stage: 5, pack: 'Shopping & money' },
    { ko: '휴가', en: 'holiday', rom: 'hyu-ga', emoji: '🏖️', stage: 5, pack: 'Airport, hotel & travel' },
    { ko: '요가', en: 'yoga', rom: 'yo-ga', emoji: '🧘', stage: 5, pack: 'School & hobbies' },
    { ko: '표', en: 'ticket', rom: 'pyo', emoji: '🎫', stage: 5, pack: 'Transport & directions', note: 'Train, bus and museum tickets are all 표.' },
    { ko: '유리', en: 'glass (the material)', rom: 'yu-ri', emoji: '🪟', stage: 5, pack: 'Home & objects' },
    { ko: '이유', en: 'reason', rom: 'i-yu', emoji: '🤔', stage: 5, pack: 'Question words' },
    { ko: '무료', en: 'free (no cost)', rom: 'mu-ryo', emoji: '🆓', stage: 5, pack: 'Shopping & money', note: 'Look for 무료 on signs: it means you don’t pay!' },
    { ko: '요구르트', en: 'yoghurt', rom: 'yo-gu-reu-teu', emoji: '🥣', stage: 5, pack: 'Food & drink' },
    { ko: '뉴스', en: 'news', rom: 'nyu-seu', emoji: '📰', stage: 5, pack: 'Home & objects' },
    // Stage 6
    { ko: '아빠', en: 'dad', rom: 'a-ppa', emoji: '👨', stage: 6, pack: 'People & family', note: 'What Korean kids call their dad.' },
    { ko: '오빠', en: 'older brother (a girl says)', rom: 'o-ppa', emoji: '👦', stage: 6, pack: 'People & family', for: 'girl', note: 'Girls call an older brother (or an older boy friend) 오빠.' },
    { ko: '토끼', en: 'rabbit', rom: 'to-kki', emoji: '🐰', stage: 6, pack: 'Animals' },
    { ko: '코끼리', en: 'elephant', rom: 'ko-kki-ri', emoji: '🐘', stage: 6, pack: 'Animals' },
    { ko: '까치', en: 'magpie', rom: 'kka-chi', emoji: '🐦', stage: 6, pack: 'Animals', note: 'Magpies are Korea’s lucky bird!' },
    { ko: '꼬리', en: 'tail', rom: 'kko-ri', emoji: '🐕', stage: 6, pack: 'Animals' },
    { ko: '뿌리', en: 'root', rom: 'ppu-ri', emoji: '🌱', stage: 6, pack: 'Weather & nature' },
    { ko: '또', en: 'again', rom: 'tto', emoji: '🔁', stage: 6, pack: 'Question words' },
    { ko: '이따가', en: 'later', rom: 'i-tta-ga', emoji: '🕒', stage: 6, pack: 'Time & days', note: '“이따가 봐요!” = See you later!' },
    { ko: '싸요', en: 'it’s cheap', rom: 'ssa-yo', emoji: '🏷️', stage: 6, pack: 'Shopping & money', note: 'Useful at the market!' },
    { ko: '비싸요', en: 'it’s expensive', rom: 'bi-ssa-yo', emoji: '💸', stage: 6, pack: 'Shopping & money', note: '“너무 비싸요!” = Too expensive!' },
    { ko: '짜요', en: 'it’s salty', rom: 'jja-yo', emoji: '🧂', stage: 6, pack: 'Restaurant & café' },
    { ko: '아저씨', en: 'mister (older man)', rom: 'a-jeo-ssi', emoji: '🧔', stage: 6, pack: 'People & family', note: 'A friendly way to call a man about your parents’ age, like a taxi driver.' },
    { ko: '조끼', en: 'vest', rom: 'jo-kki', emoji: '🦺', stage: 6, pack: 'Clothes & colours' },
    { ko: '가짜', en: 'fake', rom: 'ga-jja', emoji: '🎭', stage: 6, pack: 'Describing words' },
    { ko: '뽀뽀', en: 'kiss (cute word)', rom: 'ppo-ppo', emoji: '😘', stage: 6, pack: 'People & family' },
    // Stage 7 (first 16 = lesson 7d)
    { ko: '개', en: 'dog', rom: 'gae', emoji: '🐶', stage: 7, pack: 'Animals' },
    { ko: '게', en: 'crab', rom: 'ge', emoji: '🦀', stage: 7, pack: 'Animals' },
    { ko: '새', en: 'bird', rom: 'sae', emoji: '🐦', stage: 7, pack: 'Animals' },
    { ko: '배', en: 'pear / boat / tummy', rom: 'bae', emoji: '🍐', stage: 7, pack: 'Food & drink', note: '배 has three meanings!' },
    { ko: '돼지', en: 'pig', rom: 'dwae-ji', emoji: '🐷', stage: 7, pack: 'Animals' },
    { ko: '사과', en: 'apple', rom: 'sa-gwa', emoji: '🍎', stage: 7, pack: 'Food & drink', note: '사과 also means “an apology”.' },
    { ko: '과자', en: 'snack / biscuit', rom: 'gwa-ja', emoji: '🍪', stage: 7, pack: 'Food & drink' },
    { ko: '노래', en: 'song', rom: 'no-rae', emoji: '🎵', stage: 7, pack: 'Korean culture', note: '노래방 is a karaoke room. Very popular in Korea!' },
    { ko: '카페', en: 'café', rom: 'ka-pe', emoji: '☕', stage: 7, pack: 'Restaurant & café' },
    { ko: '메뉴', en: 'menu', rom: 'me-nyu', emoji: '📋', stage: 7, pack: 'Restaurant & café' },
    { ko: '주세요', en: 'please give me', rom: 'ju-se-yo', emoji: '🙏', stage: 7, pack: 'Greetings & manners', note: '“메뉴 주세요” = Menu, please.' },
    { ko: '가게', en: 'shop', rom: 'ga-ge', emoji: '🏪', stage: 7, pack: 'Places in town' },
    { ko: '시계', en: 'clock / watch', rom: 'si-gye', emoji: '⌚', stage: 7, pack: 'Home & objects' },
    { ko: '의자', en: 'chair', rom: 'ui-ja', emoji: '🪑', stage: 7, pack: 'Home & objects' },
    { ko: '네', en: 'yes', rom: 'ne', emoji: '👍', stage: 7, pack: 'Greetings & manners' },
    { ko: '아니요', en: 'no', rom: 'a-ni-yo', emoji: '👎', stage: 7, pack: 'Greetings & manners' },
    // Stage 7 (lesson 7e)
    { ko: '뭐', en: 'what?', rom: 'mwo', emoji: '❓', stage: 7, pack: 'Question words', note: '“이거 뭐예요?” = What is this?' },
    { ko: '왜', en: 'why?', rom: 'wae', emoji: '🤷', stage: 7, pack: 'Question words' },
    { ko: '어디예요', en: 'where is it?', rom: 'eo-di-ye-yo', emoji: '📍', stage: 7, pack: 'Question words', note: '“화장실 어디예요?” = Where’s the toilet?' },
    { ko: '어때요', en: 'how is it?', rom: 'eo-ttae-yo', emoji: '🤔', stage: 7, pack: 'Question words', note: 'Ask 어때요? to find out what someone thinks.' },
    { ko: '위', en: 'up / on top', rom: 'wi', emoji: '⬆️', stage: 7, pack: 'Transport & directions' },
    { ko: '뒤', en: 'behind', rom: 'dwi', emoji: '🔙', stage: 7, pack: 'Transport & directions' },
    { ko: '귀', en: 'ear', rom: 'gwi', emoji: '👂', stage: 7, pack: 'Body & health' },
    { ko: '가위', en: 'scissors', rom: 'ga-wi', emoji: '✂️', stage: 7, pack: 'Home & objects' },
    { ko: '바위', en: 'rock', rom: 'ba-wi', emoji: '🪨', stage: 7, pack: 'Weather & nature', note: '가위바위보 = rock-paper-scissors!' },
    { ko: '더워요', en: 'it’s hot', rom: 'deo-wo-yo', emoji: '🥵', stage: 7, pack: 'Weather & nature' },
    { ko: '추워요', en: 'it’s cold', rom: 'chu-wo-yo', emoji: '🥶', stage: 7, pack: 'Weather & nature', note: 'Korean winters are very cold. Pack a warm coat!' },
    { ko: '회사', en: 'company / office', rom: 'hoe-sa', emoji: '🏢', stage: 7, pack: 'Places in town' },
    { ko: '의사', en: 'doctor', rom: 'ui-sa', emoji: '🧑‍⚕️', stage: 7, pack: 'Body & health' },
    { ko: '세계', en: 'world', rom: 'se-gye', emoji: '🌍', stage: 7, pack: 'Airport, hotel & travel' },
    { ko: '얘기', en: 'chat / story', rom: 'yae-gi', emoji: '💬', stage: 7, pack: 'School & hobbies' },
    { ko: '교회', en: 'church', rom: 'gyo-hoe', emoji: '⛪', stage: 7, pack: 'Places in town' },
    { ko: '예', en: 'yes (very polite)', rom: 'ye', emoji: '🙇', stage: 7, pack: 'Greetings & manners' },
    // Stage 8 (first 12 per learner = lesson 8c)
    { ko: '밥', en: 'rice / a meal', rom: 'bap', emoji: '🍚', stage: 8, pack: 'Food & drink', note: '“밥 먹었어요?” (Have you eaten?) is a friendly way to say hi!' },
    { ko: '물', en: 'water', rom: 'mul', emoji: '💧', stage: 8, pack: 'Food & drink', note: '“물 주세요” = Water, please.' },
    { ko: '김치', en: 'kimchi', rom: 'gim-chi', emoji: '🥬', stage: 8, pack: 'Food & drink' },
    { ko: '빵', en: 'bread', rom: 'ppang', emoji: '🍞', stage: 8, pack: 'Food & drink' },
    { ko: '떡볶이', en: 'spicy rice cakes', rom: 'tteok-bo-kki', emoji: '🌶️', stage: 8, pack: 'Food & drink', note: 'A favourite Korean street food.' },
    { ko: '한국', en: 'Korea', rom: 'han-guk', emoji: '🇰🇷', stage: 8, pack: 'Airport, hotel & travel' },
    { ko: '서울', en: 'Seoul', rom: 'seo-ul', emoji: '🏙️', stage: 8, pack: 'Airport, hotel & travel' },
    { ko: '사람', en: 'person', rom: 'sa-ram', emoji: '🧍', stage: 8, pack: 'People & family' },
    { ko: '엄마', en: 'mum', rom: 'eom-ma', emoji: '👩', stage: 8, pack: 'People & family' },
    { ko: '친구', en: 'friend', rom: 'chin-gu', emoji: '🧑‍🤝‍🧑', stage: 8, pack: 'People & family' },
    { ko: '형', en: 'older brother (a boy says)', rom: 'hyeong', emoji: '👦', stage: 8, pack: 'People & family', for: 'boy', note: 'Boys call an older brother (or an older boy friend) 형.' },
    { ko: '언니', en: 'older sister (a girl says)', rom: 'eon-ni', emoji: '👧', stage: 8, pack: 'People & family', for: 'girl', note: 'Girls call an older sister (or an older girl friend) 언니.' },
    { ko: '집', en: 'house / home', rom: 'jip', emoji: '🏠', stage: 8, pack: 'Home & objects' },
    // Stage 8 (lesson 8d)
    { ko: '안녕하세요', en: 'hello', rom: 'an-nyeong-ha-se-yo', emoji: '👋', stage: 8, pack: 'Greetings & manners', note: 'The polite hello, for everyone you meet.' },
    { ko: '화장실', en: 'toilet', rom: 'hwa-jang-sil', emoji: '🚻', stage: 8, pack: 'Places in town', note: '“화장실 어디예요?” = Where is the toilet?' },
    { ko: '얼마예요', en: 'how much is it?', rom: 'eol-ma-ye-yo', emoji: '💰', stage: 8, pack: 'Shopping & money', note: 'Point at something and ask “얼마예요?”' },
    { ko: '공항', en: 'airport', rom: 'gong-hang', emoji: '✈️', stage: 8, pack: 'Airport, hotel & travel' },
    { ko: '호텔', en: 'hotel', rom: 'ho-tel', emoji: '🏨', stage: 8, pack: 'Airport, hotel & travel' },
    { ko: '지하철', en: 'subway', rom: 'ji-ha-cheol', emoji: '🚇', stage: 8, pack: 'Transport & directions' },
    { ko: '편의점', en: 'convenience store', rom: 'pyeo-ni-jeom', emoji: '🏪', stage: 8, pack: 'Places in town', note: 'Korean 편의점 are everywhere, and many are open 24 hours.' },
    { ko: '병원', en: 'hospital', rom: 'byeong-won', emoji: '🏥', stage: 8, pack: 'Body & health' },
    { ko: '책', en: 'book', rom: 'chaek', emoji: '📖', stage: 8, pack: 'School & hobbies' },
    { ko: '옷', en: 'clothes', rom: 'ot', emoji: '👕', stage: 8, pack: 'Clothes & colours' },
    { ko: '꽃', en: 'flower', rom: 'kkot', emoji: '🌸', stage: 8, pack: 'Weather & nature' },
    { ko: '산', en: 'mountain', rom: 'san', emoji: '⛰️', stage: 8, pack: 'Weather & nature' },
    { ko: '눈', en: 'eye / snow', rom: 'nun', emoji: '❄️', stage: 8, pack: 'Weather & nature' },
    // Stage 9
    { ko: '감사합니다', en: 'thank you', rom: 'gam-sa-ham-ni-da', emoji: '🙏', stage: 9, pack: 'Greetings & manners', note: 'Said [감사함니다]: the ㅂ hums into an ㅁ.' },
    { ko: '괜찮아요', en: 'it’s OK / I’m fine', rom: 'gwaen-cha-na-yo', emoji: '👌', stage: 9, pack: 'Greetings & manners', note: 'Said [괜차나요]. Super useful!' },
    { ko: '맛있어요', en: 'it’s delicious', rom: 'ma-si-sseo-yo', emoji: '😋', stage: 9, pack: 'Restaurant & café', note: 'Said [마시써요]. Say it after every meal!' },
    { ko: '좋아요', en: 'good / I like it', rom: 'jo-a-yo', emoji: '👍', stage: 9, pack: 'Describing words', note: 'Said [조아요]: ㅎ goes silent before a vowel.' },
    { ko: '한국어', en: 'Korean language', rom: 'han-gu-geo', emoji: '🗣️', stage: 9, pack: 'School & hobbies', note: 'Said [한구거].' },
    { ko: '학교', en: 'school', rom: 'hak-kkyo', emoji: '🏫', stage: 9, pack: 'School & hobbies', note: 'Said [학꾜].' },
    { ko: '식당', en: 'restaurant', rom: 'sik-ttang', emoji: '🍽️', stage: 9, pack: 'Restaurant & café', note: 'Said [식땅].' },
    { ko: '약국', en: 'pharmacy', rom: 'yak-kkuk', emoji: '💊', stage: 9, pack: 'Body & health', note: 'Said [약꾹]. Look for the green 약 sign.' },
    { ko: '같이', en: 'together', rom: 'ga-chi', emoji: '🤝', stage: 9, pack: 'Describing words', note: 'Said [가치]. “같이 가요!” = Let’s go together!' },
    { ko: '축하해요', en: 'congratulations', rom: 'chu-ka-hae-yo', emoji: '🎉', stage: 9, pack: 'Greetings & manners', note: 'Said [추카해요]. “생일 축하해요!” = Happy birthday!' },
    { ko: '음악', en: 'music', rom: 'eu-mak', emoji: '🎶', stage: 9, pack: 'Korean culture', note: 'Said [으막].' },
    { ko: '설날', en: 'Lunar New Year', rom: 'seol-lal', emoji: '🧧', stage: 9, pack: 'Korean culture', note: 'Said [설랄]. Korea’s biggest family holiday.' },
    { ko: '연락', en: 'contact / keep in touch', rom: 'yeol-lak', emoji: '📱', stage: 9, pack: 'School & hobbies', note: 'Said [열락].' },
    { ko: '작년', en: 'last year', rom: 'jang-nyeon', emoji: '📆', stage: 9, pack: 'Time & days', note: 'Said [장년].' },
    { ko: '해돋이', en: 'sunrise', rom: 'hae-do-ji', emoji: '🌅', stage: 9, pack: 'Weather & nature', note: 'Said [해도지].' }
  ];

  // Stage 8: the 7 ending sounds. family = letters that sound like this one at the bottom
  const finals = [
    { f: 'ㄴ', n: 1, rom: 'n', ex: '산', tip: 'Your tongue touches just behind your top teeth: "n" as in "sun".',
      words: [['산', 'mountain'], ['눈', 'eye / snow'], ['한국', 'Korea']] },
    { f: 'ㅁ', n: 2, rom: 'm', ex: '밤', tip: 'Close your lips and hum: "m" as in "mum".',
      words: [['밤', 'night'], ['김치', 'kimchi'], ['사람', 'person']] },
    { f: 'ㅇ', n: 3, rom: 'ng', ex: '방', tip: 'The bell rings! "ng" as in "sing". Remember: ㅇ is silent at the top but rings at the bottom.',
      words: [['방', 'room'], ['빵', 'bread'], ['공항', 'airport']] },
    { f: 'ㄹ', n: 4, rom: 'l', ex: '달', tip: 'At the bottom, ㄹ is an "l": tongue up behind your teeth, as in "doll".',
      words: [['달', 'moon'], ['물', 'water'], ['서울', 'Seoul']] },
    { f: 'ㄱ', n: 5, rom: 'k', ex: '박', family: 'ㄱ ㅋ ㄲ', tip: 'Stop the sound at the back of your throat, like the "k" in "book", but don’t let the air out.',
      words: [['책', 'book'], ['부엌', 'kitchen'], ['밖', 'outside']] },
    { f: 'ㄷ', n: 6, rom: 't', ex: '받', family: 'ㄷ ㅌ ㅅ ㅆ ㅈ ㅊ ㅎ', tip: 'Seven letters all stop the same way: tongue behind your teeth, like the "t" in "hot", with no puff.',
      words: [['옷', 'clothes'], ['꽃', 'flower'], ['낮', 'daytime']] },
    { f: 'ㅂ', n: 7, rom: 'p', ex: '밥', family: 'ㅂ ㅍ', tip: 'Close your lips and stop, like the "p" in "top", with no puff.',
      words: [['밥', 'rice / meal'], ['집', 'house'], ['앞', 'in front']] }
  ];
  const doubleFinals = [
    ['닭', '닥', 'chicken'], ['값', '갑', 'price'], ['앉아요', '안자요', 'sit down'],
    ['읽어요', '일거요', 'read'], ['없어요', '업써요', 'there isn’t any']
  ];

  // Stage 9: sound rules. items: [spelled, said, meaning, [wrong answers]]
  const rules = {
    link: { name: 'Linking', ko: '연음',
      text: 'When a block ends with a bottom letter and the next block starts with a silent <span class="ko">ㅇ</span>, the bottom letter <b>slides over</b> to fill the empty spot.',
      items: [['한국어', '한구거', 'Korean language', ['한국어', '한궁어']], ['음악', '으막', 'music', ['음악', '은악']],
        ['발음', '바름', 'pronunciation', ['발음', '발름']], ['먹어요', '머거요', 'I eat', ['먹어요', '멍어요']], ['옷이', '오시', 'clothes (as the subject)', ['옷이', '오디']]] },
    nasal: { name: 'Humming', ko: '비음화',
      text: 'When a stop sound (<span class="ko">ㄱ ㄷ ㅂ</span>) meets <span class="ko">ㄴ</span> or <span class="ko">ㅁ</span>, it starts <b>humming</b> too: <span class="ko">ㄱ→ㅇ, ㄷ→ㄴ, ㅂ→ㅁ</span>.',
      items: [['감사합니다', '감사함니다', 'thank you', ['감사합니다', '감사할니다']], ['한국말', '한궁말', 'Korean (spoken)', ['한국말', '한굼말']],
        ['입니다', '임니다', 'it is', ['입니다', '인니다']], ['작년', '장년', 'last year', ['작년', '작련']], ['거짓말', '거진말', 'a lie', ['거짓말', '거짐말']]] },
    aspir: { name: 'Puff power', ko: '격음화',
      text: '<span class="ko">ㅎ</span> gives its puff of air to the letter next to it: <span class="ko">ㄱ+ㅎ → ㅋ</span>, <span class="ko">ㅎ+ㄷ → ㅌ</span>, <span class="ko">ㅂ+ㅎ → ㅍ</span>.',
      items: [['좋다', '조타', 'good', ['좋다', '조다']], ['축하해요', '추카해요', 'congratulations', ['축하해요', '추가해요']],
        ['입학', '이팍', 'starting school', ['입학', '이박']], ['놓고', '노코', 'put it down and…', ['놓고', '노고']]] },
    palatal: { name: 'Ch-change', ko: '구개음화',
      text: 'When a bottom <span class="ko">ㄷ</span> or <span class="ko">ㅌ</span> meets <span class="ko">이</span>, it turns into <span class="ko">ㅈ</span> or <span class="ko">ㅊ</span>.',
      items: [['같이', '가치', 'together', ['같이', '가티']], ['굳이', '구지', 'on purpose', ['굳이', '구디']], ['해돋이', '해도지', 'sunrise', ['해돋이', '해도디']]] },
    liquid: { name: 'Double L', ko: '유음화',
      text: 'When <span class="ko">ㄴ</span> and <span class="ko">ㄹ</span> meet, the <span class="ko">ㄴ</span> changes into <span class="ko">ㄹ</span>. Two L sounds!',
      items: [['설날', '설랄', 'Lunar New Year', ['설날', '선날']], ['신라', '실라', 'Silla (an ancient kingdom)', ['신라', '신나']],
        ['연락', '열락', 'contact', ['연락', '연낙']], ['편리', '펼리', 'convenience', ['편리', '편니']]] },
    tense: { name: 'Tight squeeze', ko: '경음화',
      text: 'After a stop sound (<span class="ko">ㄱ ㄷ ㅂ</span>), the next <span class="ko">ㄱ ㄷ ㅂ ㅅ ㅈ</span> gets squeezed <b>tight</b>: <span class="ko">ㄲ ㄸ ㅃ ㅆ ㅉ</span>.',
      items: [['학교', '학꾜', 'school', ['학교', '항교']], ['식당', '식땅', 'restaurant', ['식당', '식탕']],
        ['약국', '약꾹', 'pharmacy', ['약국', '양국']], ['국밥', '국빱', 'rice soup', ['국밥', '국팝']]] }
  };

  // Passport stamps. Stages 1–9 earn a travel stamp each; the last three come from the Games tab.
  // pin: where the stage sits on the Korea map (percent of width / height)
  const stamps = [
    { id: 'airport', stage: 1, label: 'Take off!', pin: [42.8, 22.3] },
    { id: 'subway', stage: 2, label: 'Subway rider', pin: [47.7, 36.1] },
    { id: 'hotel', stage: 3, label: 'Checked in', pin: [41.3, 51.9] },
    { id: 'store', stage: 4, label: 'Snack stop', pin: [44.3, 69.6] },
    { id: 'cafe', stage: 5, label: 'Café break', pin: [25.0, 82.4] },
    { id: 'bbq', stage: 6, label: 'BBQ feast', pin: [69.2, 55.6] },
    { id: 'market', stage: 7, label: 'Market day', pin: [69.3, 39.9] },
    { id: 'directions', stage: 8, label: 'Path finder', pin: [64.3, 47.8] },
    { id: 'taxi', stage: 9, label: 'Hangul graduate', pin: [61.6, 14.9] },
    { id: 'palace', game: 'memory', goal: 5, label: 'Memory master', how: 'Win Memory Match 5 times' },
    { id: 'friend', game: 'swipe', goal: 50, label: 'Card champion', how: 'Know 50 Swipe Cards' },
    { id: 'help', game: 'speed', goal: 15, label: 'Speed reader', how: 'Score 15 in Speed Read' }
  ];

  const avatars = [
    { id: 'panda', label: 'Panda' }, { id: 'fox', label: 'Fox' },
    { id: 'whitetiger', label: 'White tiger' }, { id: 'axolotl', label: 'Axolotl' },
    { id: 'lion', label: 'Lion' }, { id: 'gorilla', label: 'Gorilla' },
    { id: 'alpaca', label: 'Alpaca' }, { id: 'monkey', label: 'Monkey' }
  ];

  // Anime pictures that exist so far. The app only looks in assets/anime/ for these;
  // anything else quietly uses the cute picture (and no 404s in the console).
  const animeHas = [
    'logo.webp', 'icon-192.webp',
    'mascot/horangi-wave.webp', 'mascot/horangi-cheer.webp', 'mascot/horangi-think.webp',
    'mascot/horangi-point.webp', 'mascot/horangi-thumbs.webp', 'mascot/horangi-sad.webp', 'mascot/horangi-sleep.webp',
    'avatars/panda.webp', 'avatars/fox.webp', 'avatars/whitetiger.webp', 'avatars/axolotl.webp',
    'avatars/lion.webp', 'avatars/gorilla.webp', 'avatars/alpaca.webp', 'avatars/monkey.webp',
    'mnemonics/mn-i.webp', 'mnemonics/mn-a.webp', 'mnemonics/mn-eo.webp'
  ];

  window.HQ_DATA = { letters, stages, words, avatars, finals, doubleFinals, rules, stamps, animeHas, WORD_GOAL: 1000 };
})();
