/* 한글 Quest — Essentials: the survival vocabulary, sorted by job.
   Always open, never locked, no order to follow. A child can dip in on the plane.

   Organised the way a phrasebook should be: what each word DOES in a sentence.
   Rows are [ko, romanisation, english, emoji?, note?].                            */
(function () {
  const W = rows => rows.map(r => ({ ko: r[0], rom: r[1], en: r[2], emoji: r[3] || '💬', note: r[4] || '' }));

  const groups = [
    /* ================= 1. THE CORE BUILDING BLOCKS ================= */
    { id: 'core', title: 'The Core Building Blocks', sub: 'Action & identity', emoji: '🧱', icon: 'ess-core',
      blurb: 'The words that carry the meaning. Nothing happens in a sentence without these.',
      sections: [

        { id: 'v1', title: 'The ten verbs you cannot live without', kind: 'Verbs', emoji: '⚡', icon: 'ess-verbs',
          note: 'If you learn nothing else, learn these. Almost any sentence you need on the trip uses one of them.',
          words: W([
            ['이에요', 'ieyo', 'is / am / are', '🟰', 'After a consonant. 예요 after a vowel.'],
            ['있어요', 'isseoyo', 'there is / I have', '✅'],
            ['없어요', 'eopseoyo', "there isn't / I don't have", '❌'],
            ['해요', 'haeyo', 'do', '🔧'],
            ['가요', 'gayo', 'go', '🚶'],
            ['와요', 'wayo', 'come', '👉'],
            ['먹어요', 'meogeoyo', 'eat', '🍚'],
            ['마셔요', 'masyeoyo', 'drink', '🥤'],
            ['봐요', 'bwayo', 'see / watch / read', '👀'],
            ['주세요', 'juseyo', 'please give me', '🤲', 'Put any noun in front: 물 주세요.'],
            ['필요해요', 'piryohaeyo', 'need', '🆘'],
            ['원해요', 'wonhaeyo', 'want (a thing)', '🙏'],
            ['하고 싶어요', 'hago sipeoyo', 'want to do', '💭'],
            ['할 수 있어요', 'hal su isseoyo', 'can do', '💪'],
            ['못 해요', 'mot haeyo', "can't do", '🚫'],
            ['알아요', 'arayo', 'know', '💡'],
            ['몰라요', 'mollayo', "don't know", '🤷']
          ]) },

        { id: 'v2', title: 'The next fifteen verbs', kind: 'Verbs', emoji: '🏃', icon: 'ess-verbs2',
          note: 'Once the first ten are automatic, these carry almost everything else a child needs to say.',
          words: W([
            ['말해요', 'malhaeyo', 'say / speak', '💬'],
            ['들어요', 'deureoyo', 'hear / listen', '👂'],
            ['읽어요', 'ilgeoyo', 'read', '📖'],
            ['써요', 'sseoyo', 'write / use', '✍️'],
            ['사요', 'sayo', 'buy', '🛒'],
            ['찾아요', 'chajayo', 'look for / find', '🔎'],
            ['기다려요', 'gidaryeoyo', 'wait', '⏳'],
            ['도와줘요', 'dowajwoyo', 'help', '🤝'],
            ['열어요', 'yeoreoyo', 'open', '🚪'],
            ['닫아요', 'dadayo', 'close', '🔒'],
            ['타요', 'tayo', 'ride / get on', '🚌'],
            ['내려요', 'naeryeoyo', 'get off', '⬇️'],
            ['자요', 'jayo', 'sleep', '😴'],
            ['일어나요', 'ireonayo', 'get up', '🌅'],
            ['줘요', 'jwoyo', 'give', '🎁'],
            ['받아요', 'badayo', 'receive', '📬'],
            ['좋아해요', 'joahaeyo', 'like', '💖']
          ]) },

        { id: 'n1', title: 'People', kind: 'Nouns', emoji: '👨‍👩‍👧', icon: 'ess-people',
          note: 'Who you are talking about, or shouting for.',
          words: W([
            ['사람', 'saram', 'person', '🧍'],
            ['친구', 'chingu', 'friend', '🧑‍🤝‍🧑'],
            ['가족', 'gajok', 'family', '👨‍👩‍👧'],
            ['엄마', 'eomma', 'mum', '👩'],
            ['아빠', 'appa', 'dad', '👨'],
            ['동생', 'dongsaeng', 'younger brother or sister', '🧒'],
            ['할머니', 'halmeoni', 'grandmother', '👵'],
            ['할아버지', 'harabeoji', 'grandfather', '👴'],
            ['선생님', 'seonsaengnim', 'teacher', '🧑‍🏫'],
            ['학생', 'haksaeng', 'student', '🎒'],
            ['아이', 'ai', 'child', '🧒'],
            ['어른', 'eoreun', 'grown-up', '🧑'],
            ['아저씨', 'ajeossi', 'mister (a grown man)', '👨‍💼'],
            ['아주머니', 'ajumeoni', 'ma’am (a grown woman)', '👩‍💼'],
            ['의사', 'uisa', 'doctor', '🩺'],
            ['경찰', 'gyeongchal', 'police officer', '👮'],
            ['직원', 'jigwon', 'staff member', '🧑‍💼']
          ]) },

        { id: 'n2', title: 'Places you actually need', kind: 'Nouns', emoji: '📍', icon: 'ess-places',
          note: 'The ones worth knowing before you land.',
          words: W([
            ['화장실', 'hwajangsil', 'toilet', '🚻', 'The single most useful noun on this page.'],
            ['호텔', 'hotel', 'hotel', '🏨'],
            ['역', 'yeok', 'station', '🚉'],
            ['공항', 'gonghang', 'airport', '✈️'],
            ['병원', 'byeongwon', 'hospital', '🏥'],
            ['약국', 'yakguk', 'pharmacy', '💊'],
            ['가게', 'gage', 'shop', '🏪'],
            ['식당', 'sikdang', 'restaurant', '🍽️'],
            ['학교', 'hakgyo', 'school', '🏫'],
            ['집', 'jip', 'home / house', '🏠'],
            ['방', 'bang', 'room', '🚪'],
            ['공원', 'gongwon', 'park', '🌳'],
            ['은행', 'eunhaeng', 'bank', '🏦'],
            ['시장', 'sijang', 'market', '🧺'],
            ['버스 정류장', 'beoseu jeongnyujang', 'bus stop', '🚏'],
            ['출구', 'chulgu', 'exit', '🚪'],
            ['입구', 'ipgu', 'entrance', '🚪']
          ]) },

        { id: 'n3', title: 'Food and drink', kind: 'Nouns', emoji: '🍜', icon: 'ess-food',
          note: 'Enough to order a meal and stay fed for two weeks.',
          words: W([
            ['물', 'mul', 'water', '💧'],
            ['밥', 'bap', 'rice / a meal', '🍚'],
            ['빵', 'ppang', 'bread', '🍞'],
            ['고기', 'gogi', 'meat', '🥩'],
            ['생선', 'saengseon', 'fish (food)', '🐟'],
            ['계란', 'gyeran', 'egg', '🥚'],
            ['과일', 'gwail', 'fruit', '🍎'],
            ['채소', 'chaeso', 'vegetables', '🥬'],
            ['우유', 'uyu', 'milk', '🥛'],
            ['주스', 'juseu', 'juice', '🧃'],
            ['김치', 'gimchi', 'kimchi', '🌶️'],
            ['국', 'guk', 'soup', '🍲'],
            ['면', 'myeon', 'noodles', '🍜'],
            ['간식', 'gansik', 'a snack', '🍡'],
            ['설탕', 'seoltang', 'sugar', '🍬'],
            ['소금', 'sogeum', 'salt', '🧂'],
            ['얼음', 'eoreum', 'ice', '🧊']
          ]) },

        { id: 'n4', title: 'Things, money and emergencies', kind: 'Nouns', emoji: '🆘', icon: 'ess-things',
          note: 'The nouns you hope not to need, and the ones you will need every day.',
          words: W([
            ['돈', 'don', 'money', '💰'],
            ['카드', 'kadeu', 'card', '💳'],
            ['여권', 'yeogwon', 'passport', '🛂'],
            ['표', 'pyo', 'ticket', '🎫'],
            ['가방', 'gabang', 'bag', '🎒'],
            ['휴대폰', 'hyudaepon', 'mobile phone', '📱'],
            ['열쇠', 'yeolsoe', 'key', '🔑'],
            ['약', 'yak', 'medicine', '💊'],
            ['옷', 'ot', 'clothes', '👕'],
            ['신발', 'sinbal', 'shoes', '👟'],
            ['우산', 'usan', 'umbrella', '☂️'],
            ['이름', 'ireum', 'name', '🏷️'],
            ['주소', 'juso', 'address', '📮'],
            ['시간', 'sigan', 'time', '🕐'],
            ['길', 'gil', 'road / the way', '🛣️'],
            ['도움', 'doum', 'help', '🆘'],
            ['사고', 'sago', 'an accident', '🚨']
          ]) },

        { id: 'p1', title: 'Pronouns', kind: 'Pronouns', emoji: '🙋', icon: 'ess-pronouns',
          note: 'Korean drops these constantly — but you still need to recognise them, and to use them when it matters.',
          words: W([
            ['저', 'jeo', 'I / me (polite)', '🙇'],
            ['나', 'na', 'I / me (casual)', '🙋'],
            ['제', 'je', 'my (polite)', '🔖', '제 이름 = my name.'],
            ['내', 'nae', 'my (casual)', '🏷️'],
            ['너', 'neo', 'you (to a friend)', '👉'],
            ['우리', 'uri', 'we / our', '👨‍👩‍👧'],
            ['저희', 'jeohui', 'we / our (polite)', '👥'],
            ['이 사람', 'i saram', 'this person', '👤'],
            ['그 사람', 'geu saram', 'that person', '🧑'],
            ['이거', 'igeo', 'this one', '👇'],
            ['그거', 'geugeo', 'that one', '👉'],
            ['저거', 'jeogeo', 'that one over there', '👈'],
            ['누구', 'nugu', 'who', '❓'],
            ['모두', 'modu', 'everyone / all', '👥'],
            ['아무도', 'amudo', 'nobody', '🚫'],
            ['자기', 'jagi', 'oneself', '🪞'],
            ['서로', 'seoro', 'each other', '🔁']
          ]) }
      ] },

    /* ================= 2. THE NAVIGATORS ================= */
    { id: 'nav', title: 'The Navigators', sub: 'Location & quantity', emoji: '🧭', icon: 'ess-nav',
      blurb: 'Where things are and how many there are — the two questions travelling never stops asking.',
      sections: [

        { id: 'pp1', title: 'Where exactly', kind: 'Position words', emoji: '📐', icon: 'ess-position',
          note: 'Korean puts these AFTER the place: 학교 앞 = school front = in front of the school.',
          words: W([
            ['안', 'an', 'in / inside', '📦'],
            ['밖', 'bak', 'outside', '🌳'],
            ['위', 'wi', 'on / above', '⬆️'],
            ['아래', 'arae', 'under / below', '⬇️'],
            ['밑', 'mit', 'underneath', '🔽'],
            ['앞', 'ap', 'in front of', '➡️'],
            ['뒤', 'dwi', 'behind', '⬅️'],
            ['옆', 'yeop', 'next to', '↔️'],
            ['사이', 'sai', 'between', '🔀'],
            ['근처', 'geuncheo', 'near', '📍'],
            ['여기', 'yeogi', 'here', '📌'],
            ['거기', 'geogi', 'there', '📍'],
            ['저기', 'jeogi', 'over there', '🔭'],
            ['에', 'e', 'to / at (a place)', '🎯', '학교에 가요 = I go to school.'],
            ['에서', 'eseo', 'at / from (where it happens)', '🏠', '집에서 먹어요 = I eat at home.'],
            ['까지', 'kkaji', 'as far as / until', '🏁'],
            ['부터', 'buteo', 'from (a starting point)', '🚦']
          ]) },

        { id: 'num1', title: 'Counting numbers (하나, 둘, 셋)', kind: 'Numbers', emoji: '🔢', icon: 'ess-numbers1',
          note: 'The Korean set. Used for ages, hours on the clock, and counting things: 사과 세 개 = three apples.',
          words: W([
            ['하나', 'hana', 'one', '1️⃣'],
            ['둘', 'dul', 'two', '2️⃣'],
            ['셋', 'set', 'three', '3️⃣'],
            ['넷', 'net', 'four', '4️⃣'],
            ['다섯', 'daseot', 'five', '5️⃣'],
            ['여섯', 'yeoseot', 'six', '6️⃣'],
            ['일곱', 'ilgop', 'seven', '7️⃣'],
            ['여덟', 'yeodeol', 'eight', '8️⃣'],
            ['아홉', 'ahop', 'nine', '9️⃣'],
            ['열', 'yeol', 'ten', '🔟'],
            ['스물', 'seumul', 'twenty', '2️⃣0️⃣'],
            ['개', 'gae', 'counter for things', '📦', '두 개 주세요 = two of them, please.'],
            ['명', 'myeong', 'counter for people', '🧍'],
            ['마리', 'mari', 'counter for animals', '🐕'],
            ['살', 'sal', 'counter for age', '🎂'],
            ['시', 'si', 'o’clock', '🕐'],
            ['번', 'beon', 'counter for times / turns', '🔁']
          ]) },

        { id: 'num2', title: 'Money and time numbers (일, 이, 삼)', kind: 'Numbers', emoji: '💰', icon: 'ess-numbers2',
          note: 'The Sino-Korean set. Used for money, minutes, dates, phone numbers and floors.',
          words: W([
            ['일', 'il', 'one', '1️⃣'],
            ['이', 'i', 'two', '2️⃣'],
            ['삼', 'sam', 'three', '3️⃣'],
            ['사', 'sa', 'four', '4️⃣'],
            ['오', 'o', 'five', '5️⃣'],
            ['육', 'yuk', 'six', '6️⃣'],
            ['칠', 'chil', 'seven', '7️⃣'],
            ['팔', 'pal', 'eight', '8️⃣'],
            ['구', 'gu', 'nine', '9️⃣'],
            ['십', 'sip', 'ten', '🔟'],
            ['백', 'baek', 'hundred', '💯'],
            ['천', 'cheon', 'thousand', '🔢'],
            ['만', 'man', 'ten thousand', '💵', 'Korean jumps in ten-thousands: 만 원 = 10,000 won.'],
            ['원', 'won', 'won (money)', '🇰🇷'],
            ['분', 'bun', 'minute', '⏱️'],
            ['층', 'cheung', 'floor (of a building)', '🛗'],
            ['얼마예요?', 'eolmayeyo?', 'how much is it?', '💰']
          ]) }
      ] },

    /* ================= 3. THE MODIFIERS ================= */
    { id: 'mod', title: 'The Modifiers', sub: 'Detail & description', emoji: '🎨', icon: 'ess-mod',
      blurb: 'How something is, and how something is done. This is where a sentence stops being flat.',
      sections: [

        { id: 'adj1', title: 'Opposites', kind: 'Adjectives', emoji: '↔️', icon: 'ess-opposites',
          note: 'Learn them in pairs — it is half the work and twice the memory. Remember: these are already verbs, so 커요 means “is big”.',
          words: W([
            ['커요', 'keoyo', 'be big', '🐘'],
            ['작아요', 'jagayo', 'be small', '🐜'],
            ['많아요', 'manayo', 'be a lot', '➕'],
            ['적어요', 'jeogeoyo', 'be a little', '➖'],
            ['뜨거워요', 'tteugeowoyo', 'be hot', '♨️'],
            ['차가워요', 'chagawoyo', 'be cold', '🧊'],
            ['좋아요', 'joayo', 'be good', '👍'],
            ['나빠요', 'nappayo', 'be bad', '👎'],
            ['비싸요', 'bissayo', 'be expensive', '💸'],
            ['싸요', 'ssayo', 'be cheap', '🪙'],
            ['가까워요', 'gakkawoyo', 'be near', '📍'],
            ['멀어요', 'meoreoyo', 'be far', '🛣️'],
            ['빨라요', 'ppallayo', 'be fast', '💨'],
            ['느려요', 'neuryeoyo', 'be slow', '🐢'],
            ['쉬워요', 'swiwoyo', 'be easy', '😌'],
            ['어려워요', 'eoryeowoyo', 'be difficult', '😵'],
            ['무거워요', 'mugeowoyo', 'be heavy', '🪨', 'Its opposite, 가벼워요 (be light), is worth learning with it.']
          ]) },

        { id: 'adj2', title: 'Describing anything', kind: 'Adjectives', emoji: '✨', icon: 'ess-describe',
          note: 'The words you reach for when someone asks 어때요? — how is it?',
          words: W([
            ['맛있어요', 'masisseoyo', 'be delicious', '😋'],
            ['매워요', 'maewoyo', 'be spicy', '🌶️'],
            ['예뻐요', 'yeppeoyo', 'be pretty', '🌸'],
            ['재미있어요', 'jaemiisseoyo', 'be fun', '😄'],
            ['아파요', 'apayo', 'be sore / hurt', '🤕'],
            ['바빠요', 'bappayo', 'be busy', '🏃'],
            ['피곤해요', 'pigonhaeyo', 'be tired', '😪'],
            ['배고파요', 'baegopayo', 'be hungry', '🍽️'],
            ['새로워요', 'saerowoyo', 'be new', '🆕'],
            ['오래됐어요', 'oraedwaesseoyo', 'be old (a thing)', '🕰️'],
            ['깨끗해요', 'kkaekkeuthaeyo', 'be clean', '🫧'],
            ['더러워요', 'deoreowoyo', 'be dirty', '🧽'],
            ['조용해요', 'joyonghaeyo', 'be quiet', '🤫'],
            ['시끄러워요', 'sikkeureowoyo', 'be noisy', '📢'],
            ['위험해요', 'wiheomhaeyo', 'be dangerous', '⚠️'],
            ['안전해요', 'anjeonhaeyo', 'be safe', '🛡️'],
            ['친절해요', 'chinjeolhaeyo', 'be kind', '😇']
          ]) },

        { id: 'adv1', title: 'When', kind: 'Adverbs', emoji: '🕐', icon: 'ess-when',
          note: 'Time words go near the start of the sentence, before the verb.',
          words: W([
            ['지금', 'jigeum', 'now', '⏱️'],
            ['나중에', 'najunge', 'later', '🕘'],
            ['오늘', 'oneul', 'today', '📍'],
            ['내일', 'naeil', 'tomorrow', '➡️'],
            ['어제', 'eoje', 'yesterday', '⬅️'],
            ['아침', 'achim', 'morning', '🌅'],
            ['점심', 'jeomsim', 'midday / lunchtime', '🕛'],
            ['저녁', 'jeonyeok', 'evening', '🌆'],
            ['밤', 'bam', 'night', '🌙'],
            ['먼저', 'meonjeo', 'first', '1️⃣'],
            ['다음에', 'daeume', 'next time', '📆'],
            ['아직', 'ajik', 'not yet / still', '⏳'],
            ['벌써', 'beolsseo', 'already', '⚡'],
            ['곧', 'got', 'soon', '🔜'],
            ['오래', 'orae', 'for a long time', '🕰️'],
            ['잠깐', 'jamkkan', 'for a moment', '⏸️'],
            ['언제', 'eonje', 'when', '❓']
          ]) },

        { id: 'adv2', title: 'How and how often', kind: 'Adverbs', emoji: '🔁', icon: 'ess-howoften',
          note: 'Drop these straight in front of the verb: 천천히 말해 주세요.',
          words: W([
            ['빨리', 'ppalli', 'quickly', '💨'],
            ['천천히', 'cheoncheonhi', 'slowly', '🐢'],
            ['잘', 'jal', 'well', '👍'],
            ['많이', 'mani', 'a lot', '➕'],
            ['조금', 'jogeum', 'a little', '🤏'],
            ['너무', 'neomu', 'too (much)', '🔥'],
            ['아주', 'aju', 'very', '❗'],
            ['진짜', 'jinjja', 'really', '😮'],
            ['같이', 'gachi', 'together', '🤝'],
            ['혼자', 'honja', 'alone', '🧍'],
            ['항상', 'hangsang', 'always', '♾️'],
            ['보통', 'botong', 'usually', '📊'],
            ['가끔', 'gakkeum', 'sometimes', '🌗'],
            ['거의', 'geoui', 'almost / hardly', '📐'],
            ['전혀', 'jeonhyeo', 'not at all', '🚫'],
            ['다시', 'dasi', 'again', '🔁'],
            ['또', 'tto', 'again / also', '➕']
          ]) }
      ] },

    /* ================= 4. THE GLUE ================= */
    { id: 'glue', title: 'The Glue', sub: 'Structure & flow', emoji: '🔗', icon: 'ess-glue',
      blurb: 'What turns one-word answers into conversation — and what makes you sound like a person rather than a phrasebook.',
      sections: [

        { id: 'con1', title: 'Joining words', kind: 'Conjunctions', emoji: '➕', icon: 'ess-joining',
          note: 'Most of these start the second sentence rather than sitting in the middle — very different from English.',
          words: W([
            ['그리고', 'geurigo', 'and', '➕'],
            ['하고', 'hago', 'and (between two nouns)', '🔗', '빵하고 우유 = bread and milk.'],
            ['그런데', 'geureonde', 'but / by the way', '↩️'],
            ['하지만', 'hajiman', 'however', '⚖️'],
            ['그래서', 'geuraeseo', 'so / therefore', '➡️'],
            ['왜냐하면', 'waenyahamyeon', 'because', '💡'],
            ['때문에', 'ttaemune', 'because of', '📌'],
            ['또는', 'ttoneun', 'or', '🔀'],
            ['아니면', 'animyeon', 'or else', '🔃'],
            ['그럼', 'geureom', 'in that case', '👉'],
            ['만약에', 'manyage', 'if', '❔'],
            ['그때', 'geuttae', 'at that time', '⏳'],
            ['그다음에', 'geudaeume', 'after that', '⏭️'],
            ['처음에는', 'cheoeumeneun', 'at first', '1️⃣'],
            ['마지막에', 'majimage', 'in the end', '🏁'],
            ['예를 들면', 'yereul deulmyeon', 'for example', '📝'],
            ['그러니까', 'geureonikka', 'I mean / that’s why', '🗣️']
          ]) },

        { id: 'int1', title: 'Please, thank you, sorry', kind: 'Essential phrases', emoji: '🙏', icon: 'ess-please',
          note: 'The eight phrases that will get a child through almost any encounter in Korea.',
          words: W([
            ['안녕하세요', 'annyeonghaseyo', 'hello', '🙇'],
            ['감사합니다', 'gamsahamnida', 'thank you', '🙏'],
            ['죄송합니다', 'joesonghamnida', "I'm sorry", '🙇'],
            ['실례합니다', 'sillyehamnida', 'excuse me', '✋'],
            ['저기요', 'jeogiyo', 'excuse me (to a stranger)', '📣'],
            ['네', 'ne', 'yes', '✅'],
            ['아니요', 'aniyo', 'no', '❌'],
            ['괜찮아요', 'gwaenchanayo', "it's okay", '👌'],
            ['도와주세요', 'dowajuseyo', 'please help me', '🆘'],
            ['천천히 말해 주세요', 'cheoncheonhi malhae juseyo', 'please speak slowly', '🐢'],
            ['다시 말해 주세요', 'dasi malhae juseyo', 'please say it again', '🔁'],
            ['한국말 잘 못해요', 'hangungmal jal mothaeyo', "I don't speak Korean well", '😅'],
            ['영어 할 수 있어요?', 'yeongeo hal su isseoyo?', 'do you speak English?', '🔤'],
            ['이게 뭐예요?', 'ige mwoyeyo?', 'what is this?', '❓'],
            ['어디예요?', 'eodiyeyo?', 'where is it?', '📍'],
            ['안녕히 계세요', 'annyeonghi gyeseyo', 'goodbye (as you leave)', '👋'],
            ['안녕히 가세요', 'annyeonghi gaseyo', 'goodbye (to someone leaving)', '🚶']
          ]) },

        { id: 'int2', title: 'Sounding like a real person', kind: 'Fillers & reactions', emoji: '😮', icon: 'ess-fillers',
          note: 'Nobody teaches these, and they are exactly what makes a child sound Korean rather than translated.',
          words: W([
            ['아', 'a', 'ah', '💭'],
            ['어…', 'eo…', 'um…', '😐'],
            ['음…', 'eum…', 'hmm…', '🤔'],
            ['그…', 'geu…', 'er… (buying time)', '⏳'],
            ['진짜?', 'jinjja?', 'really?', '😮'],
            ['정말요?', 'jeongmaryo?', 'really? (polite)', '😯'],
            ['대박', 'daebak', 'wow / amazing', '🤩'],
            ['헐', 'heol', 'no way', '😱'],
            ['맞아요', 'majayo', "that's right", '✔️'],
            ['그래요?', 'geuraeyo?', 'oh really?', '🙂'],
            ['그렇구나', 'geureokuna', 'ah, I see', '💡'],
            ['알겠어요', 'algesseoyo', 'got it', '👌'],
            ['글쎄요', 'geulsseyo', 'hmm, not sure', '🤷'],
            ['잠깐만요', 'jamkkanmanyo', 'just a moment', '✋'],
            ['화이팅', 'hwaiting', 'you can do it!', '📣'],
            ['축하해요', 'chukhahaeyo', 'congratulations', '🎉'],
            ['수고하셨어요', 'sugohasyeosseoyo', 'well done / thanks for your work', '👏']
          ]) }
      ] }
  ];


  /* One example sentence per word, so a child sees the word doing its job.
     Kept short, spoken-Korean, and built from vocabulary the app already teaches.
     [sentence, romanisation, english]                                              */
  const EX = {
    // v1 — the ten verbs
    '이에요': ['저는 학생이에요.', 'jeoneun haksaengieyo', 'I am a student.'],
    '있어요': ['동생이 있어요.', 'dongsaengi isseoyo', 'I have a younger sibling.'],
    '없어요': ['시간이 없어요.', 'sigani eopseoyo', "I haven't got time."],
    '해요': ['지금 숙제해요.', 'jigeum sukjehaeyo', "I'm doing homework now."],
    '가요': ['학교에 가요.', 'hakgyoe gayo', 'I go to school.'],
    '와요': ['친구가 와요.', 'chinguga wayo', 'My friend is coming.'],
    '먹어요': ['김밥을 먹어요.', 'gimbabeul meogeoyo', "I'm eating gimbap."],
    '마셔요': ['물을 마셔요.', 'mureul masyeoyo', "I'm drinking water."],
    '봐요': ['만화를 봐요.', 'manhwareul bwayo', "I'm reading comics."],
    '주세요': ['물 주세요.', 'mul juseyo', 'Water, please.'],
    '필요해요': ['도움이 필요해요.', 'doumi piryohaeyo', 'I need help.'],
    '원해요': ['이거 원해요.', 'igeo wonhaeyo', 'I want this one.'],
    '하고 싶어요': ['한국에 가고 싶어요.', 'hanguge gago sipeoyo', 'I want to go to Korea.'],
    '할 수 있어요': ['혼자 할 수 있어요.', 'honja hal su isseoyo', 'I can do it by myself.'],
    '못 해요': ['수영을 못 해요.', 'suyeongeul mot haeyo', "I can't swim."],
    '알아요': ['저 사람 알아요.', 'jeo saram arayo', 'I know that person.'],
    '몰라요': ['미안해요, 몰라요.', 'mianhaeyo, mollayo', "Sorry, I don't know."],

    // v2 — the next fifteen
    '말해요': ['천천히 말해요.', 'cheoncheonhi malhaeyo', 'Speak slowly.'],
    '들어요': ['음악을 들어요.', 'eumageul deureoyo', "I'm listening to music."],
    '읽어요': ['책을 읽어요.', 'chaegeul ilgeoyo', "I'm reading a book."],
    '써요': ['이름을 써요.', 'ireumeul sseoyo', "I'm writing my name."],
    '사요': ['간식을 사요.', 'gansigeul sayo', "I'm buying a snack."],
    '찾아요': ['열쇠를 찾아요.', 'yeolsoereul chajayo', "I'm looking for the key."],
    '기다려요': ['여기서 기다려요.', 'yeogiseo gidaryeoyo', "I'll wait here."],
    '도와줘요': ['좀 도와줘요!', 'jom dowajwoyo!', 'Help me a bit!'],
    '열어요': ['문을 열어요.', 'muneul yeoreoyo', "I'm opening the door."],
    '닫아요': ['창문을 닫아요.', 'changmuneul dadayo', "I'm closing the window."],
    '타요': ['버스를 타요.', 'beoseureul tayo', "I'm getting on the bus."],
    '내려요': ['다음 역에서 내려요.', 'daeum yeogeseo naeryeoyo', 'I get off at the next station.'],
    '자요': ['동생이 자요.', 'dongsaengi jayo', 'My little sibling is asleep.'],
    '일어나요': ['일곱 시에 일어나요.', 'ilgop sie ireonayo', 'I get up at seven.'],
    '줘요': ['이거 줘요.', 'igeo jwoyo', 'Give me this one.'],
    '받아요': ['선물을 받아요.', 'seonmureul badayo', "I'm getting a present."],
    '좋아해요': ['김치를 좋아해요.', 'gimchireul joahaeyo', 'I like kimchi.'],

    // n1 — people
    '사람': ['저 사람은 누구예요?', 'jeo sarameun nuguyeyo?', 'Who is that person?'],
    '친구': ['제 친구예요.', 'je chinguyeyo', "This is my friend."],
    '가족': ['우리 가족은 네 명이에요.', 'uri gajogeun ne myeongieyo', 'There are four in my family.'],
    '엄마': ['엄마, 배고파요!', 'eomma, baegopayo!', "Mum, I'm hungry!"],
    '아빠': ['아빠가 운전해요.', 'appaga unjeonhaeyo', 'Dad is driving.'],
    '동생': ['동생은 일곱 살이에요.', 'dongsaengeun ilgop sarieyo', 'My little sibling is seven.'],
    '할머니': ['할머니 집에 가요.', 'halmeoni jibe gayo', "I'm going to Grandma's house."],
    '할아버지': ['할아버지가 웃어요.', 'harabeojiga useoyo', 'Grandpa is laughing.'],
    '선생님': ['선생님, 질문 있어요.', 'seonsaengnim, jilmun isseoyo', 'Teacher, I have a question.'],
    '학생': ['저는 초등학생이에요.', 'jeoneun chodeunghaksaengieyo', "I'm a primary school pupil."],
    '아이': ['아이가 놀아요.', 'aiga norayo', 'The child is playing.'],
    '어른': ['어른한테 물어봐요.', 'eoreunhante mureobwayo', 'Ask a grown-up.'],
    '아저씨': ['아저씨, 이거 얼마예요?', 'ajeossi, igeo eolmayeyo?', 'Excuse me, how much is this?'],
    '아주머니': ['아주머니, 감사합니다.', 'ajumeoni, gamsahamnida', 'Thank you, ma’am.'],
    '의사': ['엄마는 의사예요.', 'eommaneun uisayeyo', 'Mum is a doctor.'],
    '경찰': ['경찰을 불러 주세요.', 'gyeongchareul bulleo juseyo', 'Please call the police.'],
    '직원': ['직원한테 물어볼게요.', 'jigwonhante mureobolgeyo', "I'll ask a staff member."],

    // n2 — places
    '화장실': ['화장실이 어디예요?', 'hwajangsiri eodiyeyo?', 'Where is the toilet?'],
    '호텔': ['호텔에서 자요.', 'hotereseo jayo', "We're sleeping at the hotel."],
    '역': ['역까지 멀어요?', 'yeokkkaji meoreoyo?', 'Is it far to the station?'],
    '공항': ['공항에 도착했어요.', 'gonghange dochakhaesseoyo', "We've arrived at the airport."],
    '병원': ['병원에 가야 해요.', 'byeongwone gaya haeyo', 'I have to go to the hospital.'],
    '약국': ['약국이 근처에 있어요?', 'yakgugi geuncheoe isseoyo?', 'Is there a pharmacy nearby?'],
    '가게': ['저 가게에서 사요.', 'jeo gageeseo sayo', 'I buy it at that shop.'],
    '식당': ['식당에서 만나요.', 'sikdangeseo mannayo', "Let's meet at the restaurant."],
    '학교': ['학교는 여덟 시에 시작해요.', 'hakgyoneun yeodeol sie sijakhaeyo', 'School starts at eight.'],
    '집': ['집에 가고 싶어요.', 'jibe gago sipeoyo', 'I want to go home.'],
    '방': ['제 방은 칠 층이에요.', 'je bangeun chil cheungieyo', 'My room is on the seventh floor.'],
    '공원': ['공원에서 놀아요.', 'gongwoneseo norayo', 'We play at the park.'],
    '은행': ['은행은 몇 시에 열어요?', 'eunhaengeun myeot sie yeoreoyo?', 'What time does the bank open?'],
    '시장': ['시장이 진짜 커요.', 'sijangi jinjja keoyo', 'The market is really big.'],
    '버스 정류장': ['버스 정류장이 저기 있어요.', 'beoseu jeongnyujangi jeogi isseoyo', 'The bus stop is over there.'],
    '출구': ['출구가 어디예요?', 'chulguga eodiyeyo?', 'Where is the exit?'],
    '입구': ['입구에서 기다릴게요.', 'ipgueseo gidarilgeyo', "I'll wait at the entrance."],

    // n3 — food
    '물': ['물 한 잔 주세요.', 'mul han jan juseyo', 'A glass of water, please.'],
    '밥': ['밥 먹었어요?', 'bap meogeosseoyo?', 'Have you eaten?'],
    '빵': ['아침에 빵을 먹어요.', 'achime ppangeul meogeoyo', 'I eat bread in the morning.'],
    '고기': ['고기를 좋아해요.', 'gogireul joahaeyo', 'I like meat.'],
    '생선': ['생선은 안 먹어요.', 'saengseoneun an meogeoyo', "I don't eat fish."],
    '계란': ['계란 두 개 주세요.', 'gyeran du gae juseyo', 'Two eggs, please.'],
    '과일': ['과일이 달아요.', 'gwairi darayo', 'The fruit is sweet.'],
    '채소': ['채소를 씻어요.', 'chaesoreul ssiseoyo', "I'm washing the vegetables."],
    '우유': ['우유 있어요?', 'uyu isseoyo?', 'Do you have milk?'],
    '주스': ['주스 마시고 싶어요.', 'juseu masigo sipeoyo', 'I want to drink juice.'],
    '김치': ['김치는 매워요.', 'gimchineun maewoyo', 'Kimchi is spicy.'],
    '국': ['국이 뜨거워요.', 'gugi tteugeowoyo', 'The soup is hot.'],
    '면': ['면을 더 주세요.', 'myeoneul deo juseyo', 'More noodles, please.'],
    '간식': ['간식 먹을래?', 'gansik meogeullae?', 'Want a snack?'],
    '설탕': ['설탕 넣지 마세요.', 'seoltang neochi maseyo', "Please don't put sugar in."],
    '소금': ['소금이 너무 많아요.', 'sogeumi neomu manayo', "There's too much salt."],
    '얼음': ['얼음 빼 주세요.', 'eoreum ppae juseyo', 'No ice, please.'],

    // n4 — things and emergencies
    '돈': ['돈이 없어요.', 'doni eopseoyo', "I haven't got any money."],
    '카드': ['카드 돼요?', 'kadeu dwaeyo?', 'Does card work?'],
    '여권': ['여권 여기 있어요.', 'yeogwon yeogi isseoyo', 'Here is my passport.'],
    '표': ['표 두 장 주세요.', 'pyo du jang juseyo', 'Two tickets, please.'],
    '가방': ['제 가방이 무거워요.', 'je gabangi mugeowoyo', 'My bag is heavy.'],
    '휴대폰': ['휴대폰을 잃어버렸어요.', 'hyudaeponeul ireobeoryeosseoyo', "I've lost my phone."],
    '열쇠': ['열쇠가 안 보여요.', 'yeolsoega an boyeoyo', "I can't find the key."],
    '약': ['약을 먹어야 해요.', 'yageul meogeoya haeyo', 'I have to take medicine.'],
    '옷': ['옷이 예뻐요.', 'osi yeppeoyo', 'Those clothes are pretty.'],
    '신발': ['신발을 신어요.', 'sinbareul sineoyo', "I'm putting my shoes on."],
    '우산': ['우산 가져왔어요?', 'usan gajyeowasseoyo?', 'Did you bring an umbrella?'],
    '이름': ['이름이 뭐예요?', 'ireumi mwoyeyo?', 'What is your name?'],
    '주소': ['주소를 써 주세요.', 'jusoreul sseo juseyo', 'Please write the address.'],
    '시간': ['시간이 있어요?', 'sigani isseoyo?', 'Have you got time?'],
    '길': ['길을 잃었어요.', 'gireul ireosseoyo', "I'm lost."],
    '도움': ['도움이 필요해요.', 'doumi piryohaeyo', 'I need help.'],
    '사고': ['사고가 났어요!', 'sagoga nasseoyo!', "There's been an accident!"],

    // p1 — pronouns
    '저': ['저는 뉴질랜드 사람이에요.', 'jeoneun nyujillaendeu saramieyo', 'I am from New Zealand.'],
    '나': ['나는 열 살이야.', 'naneun yeol sariya', "I'm ten."],
    '제': ['제 이름은 민준이에요.', 'je ireumeun minjunieyo', 'My name is Minjun.'],
    '내': ['내 친구야.', 'nae chinguya', "It's my friend."],
    '너': ['너는 몇 살이야?', 'neoneun myeot sariya?', 'How old are you?'],
    '우리': ['우리 같이 가자!', 'uri gachi gaja!', "Let's go together!"],
    '저희': ['저희 가족이에요.', 'jeohui gajogieyo', 'This is my family.'],
    '이 사람': ['이 사람은 제 친구예요.', 'i sarameun je chinguyeyo', 'This person is my friend.'],
    '그 사람': ['그 사람 알아요?', 'geu saram arayo?', 'Do you know that person?'],
    '이거': ['이거 얼마예요?', 'igeo eolmayeyo?', 'How much is this?'],
    '그거': ['그거 주세요.', 'geugeo juseyo', 'That one, please.'],
    '저거': ['저거 뭐예요?', 'jeogeo mwoyeyo?', 'What is that over there?'],
    '누구': ['누구세요?', 'nuguseyo?', 'Who is it?'],
    '모두': ['모두 같이 먹어요.', 'modu gachi meogeoyo', 'Everyone eats together.'],
    '아무도': ['아무도 없어요.', 'amudo eopseoyo', "There's nobody here."],
    '자기': ['자기 방을 치워요.', 'jagi bangeul chiwoyo', 'Tidy your own room.'],
    '서로': ['서로 도와줘요.', 'seoro dowajwoyo', 'We help each other.'],

    // pp1 — position
    '안': ['가방 안에 있어요.', 'gabang ane isseoyo', "It's in the bag."],
    '밖': ['밖에서 놀아요.', 'bakkeseo norayo', 'We play outside.'],
    '위': ['책상 위에 뒀어요.', 'chaeksang wie dwosseoyo', 'I put it on the desk.'],
    '아래': ['침대 아래를 봐요.', 'chimdae araereul bwayo', 'Look under the bed.'],
    '밑': ['의자 밑에 있어요.', 'uija mite isseoyo', "It's underneath the chair."],
    '앞': ['학교 앞에서 만나자.', 'hakgyo apeseo mannaja', "Let's meet in front of school."],
    '뒤': ['제 뒤에 서세요.', 'je dwie seoseyo', 'Please stand behind me.'],
    '옆': ['엄마 옆에 앉아요.', 'eomma yeope anjayo', 'I sit beside Mum.'],
    '사이': ['둘 사이에 있어요.', 'dul saie isseoyo', "It's between the two."],
    '근처': ['근처에 편의점 있어요?', 'geuncheoe pyeonuijeom isseoyo?', 'Is there a shop nearby?'],
    '여기': ['여기 앉아도 돼요?', 'yeogi anjado dwaeyo?', 'May I sit here?'],
    '거기': ['거기서 기다려.', 'geogiseo gidaryeo', 'Wait there.'],
    '저기': ['저기 보여요?', 'jeogi boyeoyo?', 'Can you see it over there?'],
    '에': ['공원에 가요.', 'gongwone gayo', "I'm going to the park."],
    '에서': ['집에서 놀아요.', 'jibeseo norayo', 'I play at home.'],
    '까지': ['다섯 시까지 놀 거야.', 'daseot sikkaji nol geoya', "I'll play until five."],
    '부터': ['아침부터 아팠어요.', 'achimbuteo apasseoyo', "It's hurt since this morning."],

    // num1 — Korean numbers
    '하나': ['하나, 둘, 셋!', 'hana, dul, set!', 'One, two, three!'],
    '둘': ['둘 다 주세요.', 'dul da juseyo', 'Both, please.'],
    '셋': ['셋까지 셀게.', 'setkkaji selge', "I'll count to three."],
    '넷': ['우리는 넷이에요.', 'urineun nesieyo', 'There are four of us.'],
    '다섯': ['다섯 시에 만나요.', 'daseot sie mannayo', "Let's meet at five."],
    '여섯': ['여섯 개 있어요.', 'yeoseot gae isseoyo', 'There are six of them.'],
    '일곱': ['동생은 일곱 살이야.', 'dongsaengeun ilgop sariya', 'My sibling is seven.'],
    '여덟': ['여덟 시에 학교에 가요.', 'yeodeol sie hakgyoe gayo', 'I go to school at eight.'],
    '아홉': ['아홉 시에 자요.', 'ahop sie jayo', 'I go to bed at nine.'],
    '열': ['저는 열 살이에요.', 'jeoneun yeol sarieyo', "I'm ten years old."],
    '스물': ['스물 넘게 있어요.', 'seumul neomge isseoyo', 'There are more than twenty.'],
    '개': ['두 개 주세요.', 'du gae juseyo', 'Two of them, please.'],
    '명': ['네 명이에요.', 'ne myeongieyo', "There are four people."],
    '마리': ['강아지 한 마리 있어요.', 'gangaji han mari isseoyo', 'I have one dog.'],
    '살': ['몇 살이에요?', 'myeot sarieyo?', 'How old are you?'],
    '시': ['지금 세 시예요.', 'jigeum se siyeyo', "It's three o'clock."],
    '번': ['한 번 더 해 주세요.', 'han beon deo hae juseyo', 'Once more, please.'],

    // num2 — Sino numbers
    '일': ['일 층에 있어요.', 'il cheunge isseoyo', "It's on the first floor."],
    '이': ['이 번 버스를 타요.', 'i beon beoseureul tayo', 'Take the number two bus.'],
    '삼': ['삼 분만 기다려요.', 'sam bunman gidaryeoyo', 'Wait just three minutes.'],
    '사': ['사 층으로 가세요.', 'sa cheungeuro gaseyo', 'Go to the fourth floor.'],
    '오': ['오 분 후에 만나요.', 'o bun hue mannayo', "See you in five minutes."],
    '육': ['육 학년이에요.', 'yuk hangnyeonieyo', "I'm in year six."],
    '칠': ['방은 칠 층이에요.', 'bangeun chil cheungieyo', 'The room is on floor seven.'],
    '팔': ['팔 번 출구예요.', 'pal beon chulguyeyo', "It's exit number eight."],
    '구': ['구 월에 가요.', 'gu wore gayo', "We're going in September."],
    '십': ['십 분 걸려요.', 'sip bun geollyeoyo', 'It takes ten minutes.'],
    '백': ['백 원이에요.', 'baek wonieyo', "It's 100 won."],
    '천': ['천 원 주세요.', 'cheon won juseyo', '1,000 won, please.'],
    '만': ['만 원이에요.', 'man wonieyo', "It's 10,000 won."],
    '원': ['오천 원이에요.', 'ocheon wonieyo', "That's 5,000 won."],
    '분': ['삼십 분 기다렸어요.', 'samsip bun gidaryeosseoyo', 'I waited thirty minutes.'],
    '층': ['몇 층이에요?', 'myeot cheungieyo?', 'Which floor?'],
    '얼마예요?': ['이거 얼마예요?', 'igeo eolmayeyo?', 'How much is this?'],

    // adj1 — opposites
    '커요': ['가방이 너무 커요.', 'gabangi neomu keoyo', 'The bag is too big.'],
    '작아요': ['신발이 작아요.', 'sinbari jagayo', 'The shoes are small.'],
    '많아요': ['사람이 많아요.', 'sarami manayo', 'There are a lot of people.'],
    '적어요': ['돈이 적어요.', 'doni jeogeoyo', "There's not much money."],
    '뜨거워요': ['조심해요, 뜨거워요!', 'josimhaeyo, tteugeowoyo!', "Careful, it's hot!"],
    '차가워요': ['물이 차가워요.', 'muri chagawoyo', 'The water is cold.'],
    '좋아요': ['날씨가 좋아요.', 'nalssiga joayo', 'The weather is good.'],
    '나빠요': ['기분이 나빠요.', 'gibuni nappayo', "I'm in a bad mood."],
    '비싸요': ['너무 비싸요!', 'neomu bissayo!', "That's too expensive!"],
    '싸요': ['여기가 더 싸요.', 'yeogiga deo ssayo', "It's cheaper here."],
    '가까워요': ['학교가 가까워요.', 'hakgyoga gakkawoyo', 'School is near.'],
    '멀어요': ['역이 멀어요?', 'yeogi meoreoyo?', 'Is the station far?'],
    '빨라요': ['지하철이 빨라요.', 'jihacheori ppallayo', 'The subway is fast.'],
    '느려요': ['버스가 느려요.', 'beoseuga neuryeoyo', 'The bus is slow.'],
    '쉬워요': ['한글은 쉬워요!', 'hangeureun swiwoyo!', 'Hangul is easy!'],
    '어려워요': ['조금 어려워요.', 'jogeum eoryeowoyo', "It's a bit difficult."],
    '무거워요': ['가방이 무거워요.', 'gabangi mugeowoyo', 'The bag is heavy.'],

    // adj2 — describing
    '맛있어요': ['진짜 맛있어요!', 'jinjja masisseoyo!', "It's really delicious!"],
    '매워요': ['이거 매워요?', 'igeo maewoyo?', 'Is this spicy?'],
    '예뻐요': ['한복이 예뻐요.', 'hanbogi yeppeoyo', 'The hanbok is pretty.'],
    '재미있어요': ['이 게임 재미있어요.', 'i geim jaemiisseoyo', 'This game is fun.'],
    '아파요': ['배가 아파요.', 'baega apayo', 'My tummy hurts.'],
    '바빠요': ['오늘은 바빠요.', 'oneureun bappayo', "I'm busy today."],
    '피곤해요': ['진짜 피곤해요.', 'jinjja pigonhaeyo', "I'm really tired."],
    '배고파요': ['너무 배고파요!', 'neomu baegopayo!', "I'm so hungry!"],
    '새로워요': ['이 신발은 새로워요.', 'i sinbareun saerowoyo', 'These shoes are new.'],
    '오래됐어요': ['이 집은 오래됐어요.', 'i jibeun oraedwaesseoyo', 'This house is old.'],
    '깨끗해요': ['방이 깨끗해요.', 'bangi kkaekkeuthaeyo', 'The room is clean.'],
    '더러워요': ['손이 더러워요.', 'soni deoreowoyo', 'My hands are dirty.'],
    '조용해요': ['도서관은 조용해요.', 'doseogwaneun joyonghaeyo', 'The library is quiet.'],
    '시끄러워요': ['여기 시끄러워요.', 'yeogi sikkeureowoyo', "It's noisy here."],
    '위험해요': ['위험해요! 조심하세요.', 'wiheomhaeyo! josimhaseyo', "It's dangerous! Be careful."],
    '안전해요': ['여기는 안전해요.', 'yeogineun anjeonhaeyo', "It's safe here."],
    '친절해요': ['선생님이 친절해요.', 'seonsaengnimi chinjeolhaeyo', 'The teacher is kind.'],

    // adv1 — when
    '지금': ['지금 가야 해요.', 'jigeum gaya haeyo', 'I have to go now.'],
    '나중에': ['나중에 얘기해요.', 'najunge yaegihaeyo', "Let's talk later."],
    '오늘': ['오늘 뭐 해요?', 'oneul mwo haeyo?', 'What are you doing today?'],
    '내일': ['내일 만나요.', 'naeil mannayo', 'See you tomorrow.'],
    '어제': ['어제 영화 봤어요.', 'eoje yeonghwa bwasseoyo', 'I watched a film yesterday.'],
    '아침': ['아침에 일어나요.', 'achime ireonayo', 'I get up in the morning.'],
    '점심': ['점심 먹었어요?', 'jeomsim meogeosseoyo?', 'Have you had lunch?'],
    '저녁': ['저녁에 만나요.', 'jeonyeoge mannayo', "Let's meet in the evening."],
    '밤': ['밤에 별이 보여요.', 'bame byeori boyeoyo', 'You can see stars at night.'],
    '먼저': ['먼저 손을 씻어요.', 'meonjeo soneul ssiseoyo', 'Wash your hands first.'],
    '다음에': ['다음에 또 와요.', 'daeume tto wayo', 'Come again next time.'],
    '아직': ['아직 안 했어요.', 'ajik an haesseoyo', "I haven't done it yet."],
    '벌써': ['벌써 다 먹었어?', 'beolsseo da meogeosseo?', "You've eaten it all already?"],
    '곧': ['곧 도착해요.', 'got dochakhaeyo', "I'll arrive soon."],
    '오래': ['오래 기다렸어요.', 'orae gidaryeosseoyo', 'I waited a long time.'],
    '잠깐': ['잠깐 기다려 주세요.', 'jamkkan gidaryeo juseyo', 'Please wait a moment.'],
    '언제': ['언제 만날까?', 'eonje mannalkka?', 'When shall we meet?'],

    // adv2 — how and how often
    '빨리': ['빨리 와!', 'ppalli wa!', 'Come quickly!'],
    '천천히': ['천천히 말해 주세요.', 'cheoncheonhi malhae juseyo', 'Please speak slowly.'],
    '잘': ['한국말 잘하네요!', 'hangungmal jalhaneyo!', 'Your Korean is good!'],
    '많이': ['많이 드세요.', 'mani deuseyo', 'Eat lots.'],
    '조금': ['조금만 주세요.', 'jogeumman juseyo', 'Just a little, please.'],
    '너무': ['너무 매워요!', 'neomu maewoyo!', "It's too spicy!"],
    '아주': ['아주 친절해요.', 'aju chinjeolhaeyo', "They're very kind."],
    '진짜': ['진짜 재미있어요!', 'jinjja jaemiisseoyo!', "It's really fun!"],
    '같이': ['같이 갈래?', 'gachi gallae?', 'Want to go together?'],
    '혼자': ['혼자 할 수 있어요.', 'honja hal su isseoyo', 'I can do it on my own.'],
    '항상': ['항상 늦어요.', 'hangsang neujeoyo', "You're always late."],
    '보통': ['보통 여덟 시에 자요.', 'botong yeodeol sie jayo', 'I usually sleep at eight.'],
    '가끔': ['가끔 축구해요.', 'gakkeum chukguhaeyo', 'I sometimes play football.'],
    '거의': ['거의 다 왔어요.', 'geoui da wasseoyo', "We're almost there."],
    '전혀': ['전혀 안 매워요.', 'jeonhyeo an maewoyo', "It's not spicy at all."],
    '다시': ['다시 말해 주세요.', 'dasi malhae juseyo', 'Please say it again.'],
    '또': ['또 만나요!', 'tto mannayo!', 'See you again!'],

    // con1 — joining words
    '그리고': ['밥 먹었어요. 그리고 잤어요.', 'bap meogeosseoyo. geurigo jasseoyo', 'I ate. And then I slept.'],
    '하고': ['빵하고 우유 주세요.', 'ppanghago uyu juseyo', 'Bread and milk, please.'],
    '그런데': ['가고 싶어요. 그런데 바빠요.', 'gago sipeoyo. geureonde bappayo', "I want to go. But I'm busy."],
    '하지만': ['매워요. 하지만 맛있어요.', 'maewoyo. hajiman masisseoyo', "It's spicy. However, it's tasty."],
    '그래서': ['아팠어요. 그래서 못 갔어요.', 'apasseoyo. geuraeseo mot gasseoyo', "I was ill. So I couldn't go."],
    '왜냐하면': ['안 가요. 왜냐하면 비가 와요.', 'an gayo. waenyahamyeon biga wayo', "I'm not going, because it's raining."],
    '때문에': ['비 때문에 못 놀아요.', 'bi ttaemune mot norayo', "We can't play because of the rain."],
    '또는': ['주스 또는 우유 주세요.', 'juseu ttoneun uyu juseyo', 'Juice or milk, please.'],
    '아니면': ['오늘, 아니면 내일 가요.', 'oneul, animyeon naeil gayo', 'Today, or else tomorrow.'],
    '그럼': ['그럼 같이 가자!', 'geureom gachi gaja!', "Then let's go together!"],
    '만약에': ['만약에 비가 오면 집에 있어요.', 'manyage biga omyeon jibe isseoyo', 'If it rains, we stay home.'],
    '그때': ['그때 진짜 무서웠어요.', 'geuttae jinjja museowosseoyo', 'It was really scary at that time.'],
    '그다음에': ['그다음에 뭐 했어?', 'geudaeume mwo haesseo?', 'What did you do after that?'],
    '처음에는': ['처음에는 어려웠어요.', 'cheoeumeneun eoryeowosseoyo', 'At first it was hard.'],
    '마지막에': ['마지막에 다 같이 웃었어요.', 'majimage da gachi useosseoyo', 'In the end we all laughed.'],
    '예를 들면': ['예를 들면 김밥이요.', 'yereul deulmyeon gimbabiyo', 'For example, gimbap.'],
    '그러니까': ['그러니까 일찍 자요.', 'geureonikka iljjik jayo', "That's why I sleep early."],

    // int1 — the essential phrases
    '안녕하세요': ['안녕하세요! 반갑습니다.', 'annyeonghaseyo! bangapseumnida', 'Hello! Nice to meet you.'],
    '감사합니다': ['도와줘서 감사합니다.', 'dowajwoseo gamsahamnida', 'Thank you for helping.'],
    '죄송합니다': ['늦어서 죄송합니다.', 'neujeoseo joesonghamnida', "I'm sorry I'm late."],
    '실례합니다': ['실례합니다, 지나갈게요.', 'sillyehamnida, jinagalgeyo', 'Excuse me, coming through.'],
    '저기요': ['저기요! 이거 떨어뜨렸어요.', 'jeogiyo! igeo tteoreotteuryeosseoyo', 'Excuse me! You dropped this.'],
    '네': ['네, 알겠어요.', 'ne, algesseoyo', 'Yes, understood.'],
    '아니요': ['아니요, 괜찮아요.', 'aniyo, gwaenchanayo', "No, I'm fine."],
    '괜찮아요': ['괜찮아요, 걱정하지 마세요.', 'gwaenchanayo, geokjeonghaji maseyo', "It's okay, don't worry."],
    '도와주세요': ['도와주세요! 길을 잃었어요.', 'dowajuseyo! gireul ireosseoyo', "Help me! I'm lost."],
    '천천히 말해 주세요': ['죄송해요, 천천히 말해 주세요.', 'joesonghaeyo, cheoncheonhi malhae juseyo', 'Sorry, please speak slowly.'],
    '다시 말해 주세요': ['다시 말해 주세요, 못 들었어요.', 'dasi malhae juseyo, mot deureosseoyo', "Say it again please, I didn't hear."],
    '한국말 잘 못해요': ['한국말 잘 못해요. 조금만 해요.', 'hangungmal jal mothaeyo. jogeumman haeyo', "I don't speak Korean well. Only a little."],
    '영어 할 수 있어요?': ['실례합니다, 영어 할 수 있어요?', 'sillyehamnida, yeongeo hal su isseoyo?', 'Excuse me, do you speak English?'],
    '이게 뭐예요?': ['이게 뭐예요? 매워요?', 'ige mwoyeyo? maewoyo?', 'What is this? Is it spicy?'],
    '어디예요?': ['화장실이 어디예요?', 'hwajangsiri eodiyeyo?', 'Where is the toilet?'],
    '안녕히 계세요': ['감사합니다, 안녕히 계세요!', 'gamsahamnida, annyeonghi gyeseyo!', 'Thank you, goodbye!'],
    '안녕히 가세요': ['안녕히 가세요, 또 오세요!', 'annyeonghi gaseyo, tto oseyo!', 'Goodbye, come again!'],

    // int2 — sounding like a real person
    '아': ['아, 그렇구나!', 'a, geureokuna!', 'Ah, I see!'],
    '어…': ['어… 잠깐만요.', 'eo… jamkkanmanyo', 'Um… just a moment.'],
    '음…': ['음… 잘 모르겠어요.', 'eum… jal moreugesseoyo', "Hmm… I'm not sure."],
    '그…': ['그… 이름이 뭐였지?', 'geu… ireumi mwoyeotji?', 'Er… what was the name again?'],
    '진짜?': ['진짜? 대박!', 'jinjja? daebak!', 'Really? Amazing!'],
    '정말요?': ['정말요? 몰랐어요.', 'jeongmaryo? mollasseoyo', "Really? I didn't know."],
    '대박': ['우와, 대박이다!', 'uwa, daebagida!', 'Wow, that’s amazing!'],
    '헐': ['헐, 진짜야?', 'heol, jinjjaya?', 'No way, seriously?'],
    '맞아요': ['맞아요, 저도 그렇게 생각해요.', 'majayo, jeodo geureoke saenggakhaeyo', 'That’s right, I think so too.'],
    '그래요?': ['그래요? 처음 들었어요.', 'geuraeyo? cheoeum deureosseoyo', "Oh really? That's news to me."],
    '그렇구나': ['아, 그렇구나. 고마워!', 'a, geureokuna. gomawo!', 'Ah, I see. Thanks!'],
    '알겠어요': ['네, 알겠어요. 할게요.', 'ne, algesseoyo. halgeyo', "Yes, got it. I'll do it."],
    '글쎄요': ['글쎄요, 잘 모르겠어요.', 'geulsseyo, jal moreugesseoyo', "Hmm, I'm not really sure."],
    '잠깐만요': ['잠깐만요, 금방 올게요.', 'jamkkanmanyo, geumbang olgeyo', "One moment, I'll be right back."],
    '화이팅': ['내일 시험이지? 화이팅!', 'naeil siheomiji? hwaiting!', "Test tomorrow, right? You've got this!"],
    '축하해요': ['생일 축하해요!', 'saengil chukhahaeyo!', 'Happy birthday!'],
    '수고하셨어요': ['오늘 수고하셨어요!', 'oneul sugohasyeosseoyo!', "You've worked hard today!"]
  };

  const sections = [];
  groups.forEach(g => g.sections.forEach(s => sections.push(Object.assign({ group: g.id, groupTitle: g.title }, s))));

  // Essentials deliberately repeats words the Path and Level 2 also teach — that is the point
  // of a survival list. Only the ones that appear nowhere else are added to the word bank.
  const all = [];
  sections.forEach(s => s.words.forEach(w => {
    if (EX[w.ko]) w.ex = { ko: EX[w.ko][0], rom: EX[w.ko][1], en: EX[w.ko][2] };
    all.push(Object.assign({ ess: s.id, pack: s.kind }, w));
  }));

  window.HQ_ESS = { groups, sections, words: all };
})();
